#! /usr/bin/perl -w

##------------------------------------------------------------------------------
# Script to insert datasets into dmg_dts (the DTS)  with the help of setup
# files to facilitate automated data loading.
# 
# Janine Aquino 9/20/2012
#
##------------------------------------------------------------------------------
use strict;
use POSIX qw(strftime);
use lib "/net/work/lib/perl/mysql";
use MySqlDatabase;
use lib "/net/work/dev/jaa/catalog_insert/src";
use ReadConfig;
my $config = ReadConfig->new();

my $msg = "";
our $options = undef;
our @dts_options = ();

# Usage statement
if ($#ARGV == -1) #no options, only program name
{
	print "Usage: $0 [-o] add_dts=dts\n";
	print "\t -o \t Output the possible options for use in the setup files.";
	print "\n\t\t Not pretty, but informative...\n";
	exit(1);
}

# Connect to database
my $database = MySqlDatabase->new("dts-update","gu3uz3","riesling.eol.ucar.edu","dmg_dts");

$database->connect();

# Read in the command line args, and call subroutines to do the work
foreach my $arg (@ARGV) {
       print $arg."\n";
       if ( $arg eq "-o") { 
           # Don't do dataset loading, just print options for setup files
	   $options = 1;
       }
       elsif ($arg =~ /add_dts=(.*)/) {
	   	unless (-e $1) { die "$1 does not exist!\n"; }
		#print "\nADD A NEW DATASET TO THE DTS\n";
		#print   "----------------------------\n";
		$msg = adddts($database, $1);
		if ($msg ne "") {
			print "Message: $msg\n";
			$database->rollback();
			$database->disconnect();
			exit(1);
		}
	}
}

if ($options) {
    $database->rollback();
    $database->disconnect();
    exit(1);
}

# If there are no errors, ask user to confirm commit changes to db.
if ($msg eq "") { 
    printf("\n\nTo commit changes, press Enter.\n");
    printf("To cancel changes, enter any value and press Enter.\n\n");
    printf(">> ");
    my $result = <STDIN>;
    
    if ($result =~ /^\s*$/) {
	$database->commit() 
    }
    else { 
	print "User Selected to Cancel!\n";
	$database->rollback();
    }
}
# If there are errors, let user know and don't commit changes.
else {print "Message: $msg\n"; $database->rollback() }
$database->disconnect();

# End of Main #
##-----------------------------------------------------------------------------
sub adddts {
        my $msg = "";	
	my $db = shift;
	my $filename = shift;

	my @ATTR;
	my @VAL;
        $config->read_config_file($filename,\@ATTR,\@VAL);
	for (my $i = 0; $i <= $#ATTR; $i++) {
	    print $ATTR[$i]."=".$VAL[$i]."\n";
	}
	print "\n";


	push @ATTR,"entry_date";
	my $now_string = strftime "%Y-%m-%d %H:%M:%S", localtime;
	push @VAL,"\"$now_string\"";

	my $table = "";
	my %results;
	my @result;

	#Insert dataset, Project Ref, Categories, Platforms, Options (Subset/Browse)
	foreach $table ("dataset","dataset_project","dataset_approve","dataset_ingest","dataset_load", "note","dataset_note") {
	    ($msg, %results) = $database->selectFull($table,'*');
	    if ($options) {
		push @dts_options, @{$results{"name"}};
		print "$table\n";
		foreach ( @{$results{"name"}} ) {print "\t".$_."\n";}
	    } else {
		$msg = insert_record($table, \@{$results{"name"}}, \@ATTR, \@VAL);
		if ($msg ne "") { return $msg; }
		if ($table eq "note") {
		   print "Get the new note_id ";
                   for (my $i = 0; $i < scalar(@ATTR); $i++) { 
		       if ($ATTR[$i] eq "entry_date") {
			   print "for entry_date = $VAL[$i]\n";
		           ($msg, @result)=$database->select($table,"note_id","entry_date = $VAL[$i]");
		           if ($msg ne "") { return $msg; }
		       }
                    }
		    push @ATTR,"note_id";
		    push @VAL,$result[0];
		}
	    }
	}

	return $msg;
}
##------------------------------------------------------------------------------
# Insert a record into a database table
sub insert_record {
    my $table = shift;
    my @attr = @{ $_[0] };
    my @ATTR = @{ $_[1] };
    my @VAL = @{ $_[2] };
    my @attribute = ();
    my @value = ();
    foreach (@attr) {
	$a = $_;
	for (my $i = 0; $i <= $#ATTR; $i++) {
		if ($a eq $ATTR[$i]) { push @attribute, $ATTR[$i]; push @value, $VAL[$i]; }
		#exceptions/inconsistencies
		if ($a eq "project_name" && $ATTR[$i] eq "name") {
		         push @attribute, "project_name"; push @value, $VAL[$i];
		}
	}
    }
    print "INSERT INTO $table(" . join(',', @attribute) . ") VALUES(" . join(',', @value) . ")\n";
    print "\nNew $table entry:\n";
    for (my $i = 0; $i < scalar(@attribute); $i++) { 
	print "\t".$attribute[$i].": ".$value[$i]."\n"; 
    }
    print "\n";
    $msg .= $database->insert($table,join(',', @attribute),join(',', @value));
    if ($msg ne "") { return $msg; }
}
##------------------------------------------------------------------------------
