#
# $Id: Makefile,v 1.1 1992/12/03 00:52:01 mark Exp $
#
#
# $Log: Makefile,v $
# Revision 1.1  1992/12/03  00:52:01  mark
# Initial revision
#
#

# Simple Makefile for xqc
# Version 1.0 alpha, 1992 May 19
# Mark Bradford, STORM Project Office
# (303) 497-8969
# bradfrd2@ncar.ucar.edu

CFLAGS = -I. -I/usr/openwin/include -g

SRCS=	xqc.c	classio.c	Skewt.c	derive.c\
	DrawText.c

OBJS=	xqc.o	classio.o	Skewt.o	derive.o\
	DrawText.o

LDR=	cc
LDFLAGS= -g
LIBS=-L/usr/openwin/lib -lX11 -lxview -lolgx
COMMAND=xqc.t

#
# Lines from here on down should not need to be changed.  They are the
# actual rules which make uses to build a.out.
#
$(COMMAND):	$(OBJS)
	$(LDR) $(LDFLAGS) -o $(COMMAND) $(OBJS) $(LIBS)

clean:
	rm -f *.o *.l

clobber:	clean
	rm -f $(COMMAND)
# DO NOT DELETE THIS LINE -- make depend depends on it.

Skewt.o: config.h /usr/include/math.h ui.h ui_symbol.h ui_param.h
Skewt.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h ui_error.h
Skewt.o: /usr/include/setjmp.h defs.h /usr/include/memory.h pd.h message.h
Skewt.o: derive.h GraphProc.h GC.h PixelCoord.h DrawText.h xqc.h
DrawText.o: /usr/include/math.h ui.h ui_symbol.h ui_param.h
DrawText.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h message.h
DrawText.o: DrawText.h sfont_1.c xqc.h
xqc.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
xqc.o: /usr/include/string.h /usr/include/sgtty.h /usr/include/sys/ttychars.h
xqc.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
xqc.o: /usr/include/sys/isa_defs.h /usr/include/sys/select.h
xqc.o: /usr/include/sys/time.h /usr/include/sys/time.h
xqc.o: /usr/include/sys/stat.h /usr/include/ctype.h /usr/include/pwd.h
xqc.o: /usr/include/unistd.h /usr/include/sys/unistd.h xqc.h GC.h
classio.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
classio.o: /usr/include/errno.h /usr/include/sys/errno.h
classio.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
classio.o: /usr/include/sys/isa_defs.h /usr/include/sys/select.h
classio.o: /usr/include/sys/time.h /usr/include/sys/time.h
classio.o: /usr/include/dirent.h /usr/include/sys/dirent.h
classio.o: /usr/include/sys/stat.h xqc.h
derive.o: /usr/include/math.h message.h derive.h
