#!/usr/bin/perl

#*******************************************************************************************************#
# dupefiles.pl                                                                                          #
#                                                                                                       #
# Looks through a listing generated by the ls -P hsi command to determine if multiple files have the    #
# same name. If a duplicate name is found, the name of that file is printed.                            #
#                                                                                                       #
# Syntax: dup_filenames_in_hsi_ls.pl [hsi ls -P listing]                                                              #
#                                                                                                       #
# 14 Jul 14: created by Morgan Garske                                                                   #
#*******************************************************************************************************#

use strict;

my %files;
while (<>) {
	if (/^FILE\s[\w\/-]+\/([\w.-]+)/) {
		if ($files{$1}) {
			print "Duplicate file: $_\n";
		}
		else {
			$files{$1} = 1;
		}
	}
}
