#!/usr/bin/perl -w

##Module-------------------------------------------------------------------------- 
# <p>The filesize_check.pl script compares the number of EBUFR records with the
# number of records in the ASCII version of the same datafile.</p>
#
# @author Linda Echo-Hawk  14 June 2011
# @version Created for the EBUFR to ASCII conversion of datasets to check issues 
#          of file size generated by the conversion scripts if ASCII files were
#          not 1.5 times larger than EBUFR files.  This script will compare the
#          number of data records for the ASCII and EBUFR versions of a data file.
#
# Usage:    filesize_check.pl <directory path> <output>
#
# Example:  filesize_check.pl /net/archive/data/esop_95/sao_specials/ results.txt
# BEWARE:   End directory path with slash
#
#
# -----------------------------------------------
# commands to check file sizes (John Allison)
# -----------------------------------------------
# soundings:
# ebrecscan < /net/archive/data/ihop/rawinsonde/nssl-class/NSSL6251900.ebufr
# ebrecscan < /net/archive/data/ihop/rawinsonde/nssl-class/NSSL6251900.ebufr | egrep '^9' | egrep ' 001/' | wc -l
# wc -l /net/archive/data/ihop/rawinsonde/nssl-class/NSSL6251900.scf
# 
# surface/precip:
# ebrecscan < /net/archive/data/esop_95/sao_specials/ES95SP_950411.ebufr
# ebrecscan < /net/archive/data/esop_95/sao_specials/ES95SP_950411.ebufr | egrep '^9' | wc -l
# wc -l /net/archive/data/esop_95/sao_specials/ES95SP_950411.qcf
#
# -----------------------------------------------
# ALGORITHM:
#   for the given directory, run ebrecscan on a given ebufr file
#   check the wc for the ascii version of the file *.*cf
#   subtract the number of header records from the ascii version
#       surface *.qcf   3 header records
#       sounding *.scf
#       precip *.pqcf
#   compare num records
#   log a message:
#       if no difference, then file size good
#       if different, then file needs to be checked
# 
##Module--------------------------------------------------------------------------
use strict;
use warnings; 

use Time::localtime;
my $current_date = ctime();

printf "\nChecking file sizes for directory $ARGV[0]\n";

open (OUT, ">$ARGV[1]") || die "Can't open file for writing\n";

my $path = $ARGV[0];
# print "PATH: $path\n";

print OUT "Comparing EBUFR records to ASCII records for $path\n on $current_date\n";
print OUT "Search for 'WARNING' to find files with different sizes\n";
print OUT "Search for 'PROBLEM' to find sounding problems\n";

my $filecount = 0;
my $ebufr_file;
my $text_file;

# ----------------------------------------------------------
# Read the directory specified in the command line and
# get a list of the EBUFR files and the ASCII files
# ----------------------------------------------------------
# should not have to open the same dir twice, but otherwise
# can't seem to get both file arrays... 
# ----------------------------------------------------------
opendir (my $RAW1,$ARGV[0]) or die("Can't read directory ".$ARGV[0]);
my @ebufr_files = grep(/\.ebufr$/i, sort(readdir($RAW1)));
closedir ($RAW1);
# test print the list
#foreach $ebufr_file(@ebufr_files)
#{
	# print OUT "$ebufr_file\n";
#}
my $ebufr_size = @ebufr_files;

opendir (my $RAW2,$ARGV[0]) or die("Can't read directory ".$ARGV[0]);
# TO DO
# need to grab the pqcf, scf and qcf files
# my @text_files = grep(/\.qcf$/i, sort(readdir($RAW2)));
my @text_files = grep(/\.p?[qs]cf$/i, sort(readdir($RAW2)));
closedir ($RAW2);
# test print the list
#foreach $text_file(@text_files)
#{
#    print OUT "$text_file\n";
#}

# ----------------------------------------------------------
# Compare the size of the file lists and make sure
# that there is an equal number of EBUFR and ASCII files
# ----------------------------------------------------------
my $text_size = @text_files;
if ($ebufr_size != $text_size)
{
	print OUT "array sizes differ:  EBUFR $ebufr_size vs. TEXT $text_size\n";
}

# ----------------------------------------------------------
# For each file in the directory, run the commands to get
# the number of file records; subtract the header records
# from the ASCII files.  Compare the number of records and
# write to the counts to the log.  Note with "WARNING" if
# there is a discrepancy between the EBUFR file and the
# ASCII file.
# ----------------------------------------------------------
my $num_ebufr_recs;
my $num_text_recs;
my $header_recs = 0;
my $is_sounding = 0;
my $is_precip = 0;
my $num_soundings = 1;

while ($filecount < $ebufr_size)
{
    # ------------------------------
    # Check the EBUFR files
    # ------------------------------
	if ( $text_files[$filecount] =~ /\.scf$/i) # sounding
	{
		$is_sounding = 1;
		$num_ebufr_recs = `/usr/local/codiac/bin/ebrecscan < $path$ebufr_files[$filecount] | egrep '^9' | egrep ' 001/' | wc -l`; 
		$num_soundings =  `grep -c 'Data Type' $path$text_files[$filecount]`;
		chomp($num_soundings);
		# print OUT "NUM SOUNDINGS: $num_soundings\n";
		$header_recs = 15;
	}
	else
	{
		$num_ebufr_recs = `/usr/local/codiac/bin/ebrecscan < $path$ebufr_files[$filecount] | egrep '^9' | wc -l`; 
		if ($text_files[$filecount] =~ /\.pqcf$/i) # precip
		{
            # precip data has zero header records
			$is_precip = 1;
		}
		else
		{
			# surface data has 3 header records
		    $header_recs = 3;
		}
	}
	# print "$ebufr_files[$filecount]: $num_ebufr_recs\n";
	chomp($num_ebufr_recs);

    # ------------------------------
    # Print out the assumptions
    # ------------------------------
	if ($filecount == 0)
	{
		print OUT "Assuming header records = $header_recs\n\n";
	}
    
	# ------------------------------
    # Now check the ASCII files
    # ------------------------------
	my $word_count = `wc -l $path$text_files[$filecount]`;
    $num_text_recs = (split(' ', $word_count))[0];

	# need to subtract header lines from $num_text_recs
	$num_text_recs -= $header_recs;

	# print "$text_files[$filecount]: $num_text_recs\n";

    # ------------------------------
    # Print out the results
    # ------------------------------
	if ($num_text_recs != $num_ebufr_recs)
	{
		print OUT "WARNING: $ebufr_files[$filecount] EBUFR: $num_ebufr_recs  TEXT: $num_text_recs\n";
	}
    else
	{
		print OUT "$ebufr_files[$filecount] EBUFR: $num_ebufr_recs  TEXT: $num_text_recs\n";  
	}
	if ($is_sounding)
	{
		print OUT "\tNUM SOUNDINGS: $num_soundings\n";
		if ($num_ebufr_recs != $num_soundings)
		{
			print OUT "\tPROBLEM: EBUFR: $num_ebufr_recs not equal SOUNDINGS: $num_soundings\n";
		}
		else
	    {
			print OUT"\tEBUFR ($num_ebufr_recs) = SOUNDINGS ($num_soundings)\n";
		}
	}

    $filecount++;
}










