#! /usr/bin/perl
#
# ./CirpasRename.pl
# There are no commandline inputs for this script, nor output.
#
# This Script renames files in the current directory matching a certain filename pattern, and prints a Renaming Report.txt file with the count of files skipped and files renamed.
#
#Used to rename files for the VOCALS 2008 project, to rename CIRPAS Twin Otter files.
#
# Version 0.1 November 2009 Luke Przygocki
# Version 0.2 December 2010 Luke Przygocki
#
# Full Description:
# Use this script to rename files in the current directory to the following filename pattern:
#
# research.CIRPAS_Otter.yyyymmddhhmm.flt_track.png
#
# The script targets (and converts to) the following filenames:
#             current file name            product name                   
#file 1 -       yymmdd_sel 1.png    =   flt_track
#file  2-       yymmdd_sel 2.png    =   3D_track
#file  4 -      yymmdd_sel 4.png    =   ac_attitude
#file  5 -      yymmdd_sel 5.png    =   ac_velocity
#file  6 -      yymmdd_sel 6.png    =   diff_pressure
#file  7 -      yymmdd_sel 7.png    =   dyn_pressure
#file  8 -      yymmdd_sel 8.png    =   static_pressure
#file  9 -      yymmdd_sel 9.png    =   Temp_Td
#file 10 -     yymmdd_sel 10.png   =  humidity_CO2
#file 11 -     yymmdd_sel 11.png   =  Temp_TAS
#file 12 -     yymmdd_sel 12.png   =  winds  

#Here are the times for each day (for the output of the new name):
#Date              Takeoff 
#		      hhmm
#Oct 16		1420
#Oct 18		1102
#Oct 19		1101
#Oct 21		1108

$renamecount, $skipcount, $totalcount = 0;
my @files;

open (DEBUG, ">>Renaming_Report.txt") || die "Can't open renaming file \n";
print DEBUG "Generated by CirpasRename.pl \n \n \n";

opendir(DIR,"./") || die "can't open current directory";
while(my $file = readdir(DIR)){
    push( @files, $file);
    $totalcount++;
}
closedir(DIR);


foreach (@files){
    if( $_ =~ /(\d+?)\_sel\s(\d{1,2})\.png/i){
	my ($date,$num,$name) = ($1, $2, $&);
	rename_files($date,$num,$name);
    }
    else
    {
#correct form of the file, otherwise skip it
	$skipcount++;
	print DEBUG "skipping $_ \n";
	next;
    }
    
}
 #Remove ., .., this script, and Renaming_Report.txt from count
$totalcount -= 4;
$skipcount -= 4;

print DEBUG "files skipped: $skipcount \n";
print DEBUG "files renamed: $renamecount \n";
print DEBUG "total files: $totalcount \n";


sub rename_files{
    my $date = shift; 
    my $filenum = shift;
    my $filename = shift;
    my $hours = translate_hours($date);
    my $newname;
    print DEBUG "hours translated: $hours\n";
    if( $filenum == 3 || $filenum > 12 || $filenum < 1  ){
	print DEBUG "skipping $filename \n";
	$skipcount++;
	return;
    }else{
	
	if( $date =~/.{10}/ ){ # if a flight time was included
	    
	    $newname = "research.CIRPAS_Otter" . "." . "20" . $date . "." . translate_name($filenum).".png";
	}
	else
	{ 
	    $newname = "research.CIRPAS_Otter" . "." . "20" . $date .$hours. "." . translate_name($filenum).".png";
	    
	}
	
	print DEBUG "Renaming $filename to $newname \n";
	$renamecount++;
	rename($filename, $newname);
	
	
    }
}

sub translate_name{
    use Switch;
    my ($num) = shift;
    
    switch ($num){
	case 1 {return "flt_track"}
	case 2 {return "3D_track"}
	case 4 {return "ac_attitude"}
	case 5 {return "ac_velocity"}
	case 6 {return "diff_pressure"}
	case 7 {return "dyn_pressure"}
	case 8 {return "static_pressure"}
	case 9 {return "Temp_Td"}
	case 10 {return "humidity_CO2"}
	case 11 {return "Temp_TAS"}
	case 12 {return "winds"}
	default {return $num}
    }	
}

sub translate_hours{
    #the launch time (hours and minutes) is based on what day it was launched
    my ($date) = shift;
    if ($date =~/1016/){return "1420"}
    if ($date =~ /1018/){return "1102"}
    if ($date =~/1019/){return "1101"}
    if ($date =~/1021/){return "1108"}
    if ($date =~//){return "9999"}
    
}
close DEBUG;
