/*
 * ChatLogGUI.java
 *
 * Created on October 23, 2007, 3:36 PM
 */
package chatscrubber;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.ListIterator;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.UIManager.*;
import javax.swing.table.TableColumn;
import javax.swing.text.StyledDocument;

/**
 *
 * @author  pmartin
 * @version 1.1
 * GUI for Chat Log Sanitation program
 */
public class ChatLogGUI extends javax.swing.JFrame {

    final String version = "1.3";
    //location of help file
    final String helpURL = "http://www.eol.ucar.edu/projects/chat_scrubber/help.html";
    textChecker checker = new textChecker();
    //boolean variables to prevent errors in program logic
    boolean fileLoaded = false;
    boolean regexLoaded = false;
    boolean fileSaved = false;
    boolean fileMatched = false;
    //Keeps track of processed files 
    ArrayList files = new ArrayList();
    //File window we will use for choosing files
    //Global so it remembers last location a file was picked from
    JFileChooser chooser;
    LinkedList<File> fileListing;
    ListIterator iter;

    //start the gui with the default regex file loaded 
    public ChatLogGUI() {
        init();
        //Set the default directory to the current working directory
        //Windows current directory is tested for first
        String directory = System.getenv("CD");
        if (directory != null) {
            chooser = new JFileChooser(directory);
        } else {
            //linux current directory
            directory = System.getenv("PWD");
            if (directory != null) {
                chooser = new JFileChooser(directory);
            } else {
                //otherwise use home of user for default directory 
                chooser = new JFileChooser();
            }
        }
        //try to load the default regex file
        if (checker.loadRegexFile(getClass().getResourceAsStream("/resources/textfiles/regex.txt"))) {
            regexLoaded = true;
        }
    }

    //used to set the initial state of the application
    private void init() {
        initComponents();
        //center application
        this.setLocationRelativeTo(null);
        //set icon for the application
        Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/images/bubbles.png"));
        setIconImage(img);

        //set next to alt+down arrow and back to alt+up arrow
        //replace to alt+r and insert to alt+i
        nextButton.setMnemonic(KeyEvent.VK_DOWN);
        backButton.setMnemonic(KeyEvent.VK_UP);
        replaceButton.setMnemonic('r');
        insertButton.setMnemonic('i');

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * AUTO-generated code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        backButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        backButton.setHorizontalTextPosition(SwingConstants.CENTER);
        nextButton = new javax.swing.JButton();
        nextButton.setVerticalTextPosition(SwingConstants.TOP);
        nextButton.setHorizontalTextPosition(SwingConstants.CENTER);
        saveButton = new javax.swing.JButton();
        replaceButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPane1 = new javax.swing.JTextPane();
        insertButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        currentFileLabel = new javax.swing.JLabel();
        previousFile = new javax.swing.JButton();
        nextFile = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        loadFile = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        showProccessed = new javax.swing.JMenuItem();
        changeSanitize = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        quit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        markLines = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        undoMenuItem = new javax.swing.JMenuItem();
        redoMenuItem = new javax.swing.JMenuItem();
        regexMenu = new javax.swing.JMenu();
        loadRegex = new javax.swing.JMenuItem();
        addRegex = new javax.swing.JMenuItem();
        printRegex = new javax.swing.JMenuItem();
        regexStats = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        about = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Scrubber");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        double xSize = (5/7)*dimension.width;
        double ySize = (5/7)*dimension.height;
        setBounds(1/7*dimension.width,1/7*dimension.height,(int)xSize,(int)ySize);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/arrow_up.png"))); // NOI18N
        backButton.setMnemonic('a');
        backButton.setText("Back");
        backButton.setToolTipText("Go to previous flagged line.");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/arrow_down.png"))); // NOI18N
        nextButton.setText("Next");
        nextButton.setToolTipText("Go to next flagged line.");
        nextButton.setMaximumSize(new java.awt.Dimension(300, 300));
        nextButton.setMinimumSize(new java.awt.Dimension(80, 80));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Dialog", 0, 12));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/save.png"))); // NOI18N
        saveButton.setText("Save Changes");
        saveButton.setToolTipText("Save changes made to text.");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        replaceButton.setFont(new java.awt.Font("Dialog", 0, 12));
        replaceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/highlight.png"))); // NOI18N
        replaceButton.setText("Replace marked with statement");
        replaceButton.setToolTipText("Replace yellow highlighted text with a generic statement");
        replaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceButtonActionPerformed(evt);
            }
        });

        textPane1.setBackground(new java.awt.Color(215, 255, 255));
        textPane1.setEditable(false);
        textPane1.setFont(new java.awt.Font("SansSerif", 1, 14));
        textPane1.setToolTipText("");
        textPane1.setSelectionColor(new java.awt.Color(255, 255, 0));

        jScrollPane1.setViewportView(textPane1);

        insertButton.setFont(new java.awt.Font("Dialog", 0, 12));
        insertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/pointer.png"))); // NOI18N
        insertButton.setText("Insert Statement at Selected Text");
        insertButton.setToolTipText("Insert a generic statement at the cursor's location or at text selected using the mouse.");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        currentFileLabel.setText("Please load a file");

        previousFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/arrow_left.png"))); // NOI18N
        previousFile.setText("Previous File");
        previousFile.setToolTipText("Load the previous file in the directory");
        previousFile.setEnabled(false);
        previousFile.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        previousFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousFileActionPerformed(evt);
            }
        });

        nextFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/arrow_right.png"))); // NOI18N
        nextFile.setText("Next File");
        nextFile.setToolTipText("Load the next file in the directory");
        nextFile.setEnabled(false);
        nextFile.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nextFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFileActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 51));

        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("File");
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuMousePressed(evt);
            }
        });

        loadFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        loadFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/folder.png"))); // NOI18N
        loadFile.setText("Load chat file");
        loadFile.setToolTipText("Load a  file to sanitize.");
        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileActionPerformed(evt);
            }
        });
        menu.add(loadFile);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/save.png"))); // NOI18N
        save.setText("Save changes");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        menu.add(save);
        menu.add(jSeparator1);

        showProccessed.setText("Show processed files");
        showProccessed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProccessedActionPerformed(evt);
            }
        });
        menu.add(showProccessed);

        changeSanitize.setText("Change sanitized statement");
        changeSanitize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSanitizeActionPerformed(evt);
            }
        });
        menu.add(changeSanitize);
        menu.add(jSeparator3);

        quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        quit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/quit.png"))); // NOI18N
        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        menu.add(quit);

        jMenuBar1.add(menu);

        editMenu.setForeground(new java.awt.Color(255, 255, 255));
        editMenu.setText("Edit");
        editMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMenuMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editMenuMousePressed(evt);
            }
        });
        editMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuActionPerformed(evt);
            }
        });

        markLines.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        markLines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/highlight.png"))); // NOI18N
        markLines.setText("Mark lines");
        markLines.setToolTipText("Mark all lines that match loaded regular expressions.");
        markLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markLinesActionPerformed(evt);
            }
        });
        editMenu.add(markLines);
        editMenu.add(jSeparator2);

        undoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        undoMenuItem.setText("undo");
        undoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(undoMenuItem);

        redoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        redoMenuItem.setText("redo");
        redoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(redoMenuItem);

        jMenuBar1.add(editMenu);

        regexMenu.setForeground(new java.awt.Color(255, 255, 255));
        regexMenu.setText("Regex");
        regexMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regexMenuMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                regexMenuMousePressed(evt);
            }
        });

        loadRegex.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        loadRegex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/folder.png"))); // NOI18N
        loadRegex.setText("Load regular expressions");
        loadRegex.setToolTipText("Load a new regular expression file.");
        loadRegex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadRegexActionPerformed(evt);
            }
        });
        regexMenu.add(loadRegex);

        addRegex.setText("Add regular expression");
        addRegex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRegexActionPerformed(evt);
            }
        });
        regexMenu.add(addRegex);

        printRegex.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        printRegex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/text.png"))); // NOI18N
        printRegex.setText("Show regular expressions");
        printRegex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printRegexActionPerformed(evt);
            }
        });
        regexMenu.add(printRegex);

        regexStats.setText("Show regex matching stats");
        regexStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regexStatsActionPerformed(evt);
            }
        });
        regexMenu.add(regexStats);

        jMenuBar1.add(regexMenu);

        helpMenu.setForeground(new java.awt.Color(255, 255, 255));
        helpMenu.setText("Help");

        help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        help.setMnemonic('H');
        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        helpMenu.add(help);
        helpMenu.add(jSeparator4);

        about.setMnemonic('A');
        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        helpMenu.add(about);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(previousFile, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nextFile, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                                    .addComponent(insertButton, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(replaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                    .addComponent(currentFileLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(currentFileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(replaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextFile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previousFile))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {insertButton, replaceButton, saveButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        save();
    }//GEN-LAST:event_saveActionPerformed

    //Show a textPane containing all of the loaded regular expressions
    private void printRegexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printRegexActionPerformed
        if (regexLoaded) {
            //display regular expressions in a scroll pane
            TextScrollPane txt = new TextScrollPane(this.getContentPane(), checker.printRegex());
        } else {
            JOptionPane.showMessageDialog(this.getContentPane(), "No Regex File has been Loaded");
        }
    }//GEN-LAST:event_printRegexActionPerformed

    //Insert sanitized statment at the location of the caret or selected text
    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        int start = textPane1.getSelectionStart();
        int end = textPane1.getSelectionEnd();
        checker.insert(start, end);
        textPane1.setCaretPosition(checker.getCurrent());
        undoMenuItem.setEnabled(checker.canUndo());
        redoMenuItem.setEnabled(checker.canRedo());
    }//GEN-LAST:event_insertButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        save();
    }//GEN-LAST:event_saveButtonActionPerformed

    //writes the modified document to a new file
    private void save() {
        if (fileLoaded) {
            checker.writeToFile(textPane1.getStyledDocument());
            JOptionPane.showMessageDialog(this.getContentPane(), "File: " + checker.getFile().getName() + ".san was written");
            //add this file to the list of processed files
            if (!fileSaved) {
                files.add(checker.getFile());
            }
            fileSaved = true;
        } else {
            JOptionPane.showMessageDialog(this.getContentPane(), "Please Load a File", "Load File", JOptionPane.ERROR_MESSAGE);
        }
    }

    //replace the current highlighted text with the sanitized statement
    private void replaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButtonActionPerformed
        if (checker.replace(textPane1.getStyledDocument())) {
            checker.markLines();
            textPane1.setCaretPosition(checker.getCurrent());
        }
        undoMenuItem.setEnabled(checker.canUndo());
        redoMenuItem.setEnabled(checker.canRedo());
    }//GEN-LAST:event_replaceButtonActionPerformed

    //load a new set of regular expressions
    private void loadRegexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadRegexActionPerformed
        if (regexLoaded) {
            if (JOptionPane.showConfirmDialog(this.getContentPane(), "Are you sure you want to load a new regex file?", "Load new regex file?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                loadRegexFile();
            }
        } else {
            loadRegexFile();
            regexLoaded = true;
        }
    }//GEN-LAST:event_loadRegexActionPerformed

    //helper method used for loading regular expressions from a file
    private void loadRegexFile() {
        FileInputStream inputStream = null;
        try {
            File f = loadFile(chooser);
            inputStream = new FileInputStream(f);
            checker.loadRegexFile(inputStream);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this.getContentPane(), ex.getMessage(), "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    //highlight previous flagged line
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        try {
            if (fileLoaded && regexLoaded) {
                checker.markLines();
                fileMatched = true;
            }
            textPane1.setCaretPosition(checker.getBack());
        } catch (Exception ex) {//GEN-LAST:event_backButtonActionPerformed
            JOptionPane.showMessageDialog(this.getContentPane(), ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
        }
    }

    //used to display a table of how many times regex were matched
    public void showStatsTable() {
        String[] columnNames = {"Regex", "Times Matched"};
        JTable table = new JTable(checker.getStatData(), columnNames);
        JScrollPane scrollPane = new JScrollPane(table);
        table.setFillsViewportHeight(true);
        JFrame frame = new JFrame();
        frame.getContentPane().add(scrollPane);
        //Set number column smaller
        TableColumn columnNumbers = table.getColumnModel().getColumn(1);
        columnNumbers.setPreferredWidth(30);
        TableColumn columnRegex = table.getColumnModel().getColumn(0);
        columnRegex.setPreferredWidth(300);
        //set size
        frame.setSize(500, 320);
        //center table
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }

    //mark all flagged lines in the current document
    private void markLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markLinesActionPerformed
        if (fileLoaded) {
            if (checker.getNumRegex() > 0) {
                int numLines = checker.markLines();
                fileMatched = true;
                if (numLines > 0) {
                    JOptionPane.showMessageDialog(this.getContentPane(), numLines + " Flagged lines have been found", "Flagged Lines", JOptionPane.INFORMATION_MESSAGE);
                    //set location to first flaggedLine
                    textPane1.setCaretPosition(checker.getCurrent());


                } else {
                    JOptionPane.showMessageDialog(this.getContentPane(), "No flagged lines were found!", "No Lines Found", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this.getContentPane(), "NO REGULAR EXPESSIONS TO MATCH AGAINST!", "LOAD REGEX FILE!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this.getContentPane(), "NO FILE HAS BEEN LOADED!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_markLinesActionPerformed

    //highlight next flagged line
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        try {
            if (fileLoaded && regexLoaded) {
                checker.markLines();
                fileMatched = true;
            }
            //set documents caret position
            textPane1.setCaretPosition(checker.getNext());
        } catch (Exception ex) {//GEN-LAST:event_nextButtonActionPerformed

            JOptionPane.showMessageDialog(this.getContentPane(), ex.getMessage(), "Message", JOptionPane.WARNING_MESSAGE);
        }
    }

    //load a chat file
    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
        if (!fileLoaded) {
            File f = loadFile(chooser);
            if (f != null) {
                fileLoaded = true;
                loadNewFile(f);
            }
        } else {
            int choice = JOptionPane.showConfirmDialog(this.getContentPane(), "Are you sure you want to load a new file?", "Load New File?", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                File f = loadFile(chooser);
                if (f != null) {
                    loadNewFile(f);
                }
            }
        }
    }//GEN-LAST:event_loadFileActionPerformed

    //Changes the state of the next and previous file buttons based on location within the file list
    private void updateNextPreviousButtons() {
        if (iter.hasNext()) {
            nextFile.setEnabled(true);
        } else {
            nextFile.setEnabled(false);
        }

        if (iter.hasPrevious()) {
            previousFile.setEnabled(true);
        } else {
            previousFile.setEnabled(false);
        }

        //checks if there is only one file in the list so set both buttons to disabled
        if (fileListing.size() == 1) {
            nextFile.setEnabled(false);
            previousFile.setEnabled(false);
        }
    }

    //updates the current file to the next file in the current directory
    private void loadNextFile() {
        if (iter.hasNext()) {
            File f = (File) iter.next();
            //check if we are in the process of reversal
            if (f.equals(checker.getFile())) {
                //increment one extra time
                if (iter.hasNext()) {
                    f = (File) iter.next();
                }
            }
            loadNewFile(f);
        }
    }

    //updates the current file to the previous file in the current directory
    private void loadPreviousFile() {
        if (iter.hasPrevious()) {
            File f = (File) iter.previous();
            //check if we are in the process of reversal
            if (f.equals(checker.getFile())) {
                //increment one extra time
                if (iter.hasPrevious()) {
                    f = (File) iter.previous();
                }
            }
            loadNewFile(f);
        }
    }

    //used to set GUI properties once a new file has been loaded
    private void loadNewFile(File f) {
        setDocument(f);
        setCurrentFileLabel();
        fileSaved = false;
        fileMatched = false;
        markLines.setEnabled(true);
        save.setEnabled(true);
        getDirectoryList();
        updateNextPreviousButtons();
    }

    //Returns a LinkedList containing all of the files in the JFileChooser's current directory
    //Also updates the iterator for this file list to the current file
    //If a file ends with .san it is ignored d
    private LinkedList getDirectoryList() {
        //resets the file listing
        fileListing = new LinkedList();

        File directory = chooser.getCurrentDirectory();

        //gets the files ignoring .san files
        File[] listing = directory.listFiles(new SanitizedFilter());
        Arrays.sort(listing);
        for (File f : listing) {
            //only adds files not directories
            if (f.isFile()) {
                fileListing.add(f);
            }
        }

        //find out the current file so we can set the iterator to the proper location
        File currentFile = checker.getFile();
        int index = fileListing.indexOf(currentFile);
        //check for the very first file
        if (index == 0) {
            //set the iterator to the begining of the list
            iter = fileListing.listIterator();
        } //check for the last file
        else if (index == fileListing.size() - 1) {
            //set the iterator to the ending of the list
            iter = fileListing.listIterator(fileListing.size());
        } //a file in between the beginning and end of the list
        else {
            //set the iterator to the index of this file
            iter = fileListing.listIterator(index);
        }
        return fileListing;
    }

    //helper method for loading a chatfile
    private void setDocument(File f) {
        try {
            textPane1.setDocument(checker.readFile(f, (StyledDocument) textPane1.getDocument()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.getContentPane(), ex.getMessage());
        }
    }

    //exit the program
    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        System.exit(0);
}//GEN-LAST:event_quitActionPerformed

    //show a JOptionPane containing version information
    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // Print out version information
        String text = "";
        text += "Chat Log Sanitizer\n\n";
        text += "Version " + version + " (released 6 July 2009)\n";
        text += "2009 Copyright (c) UCAR\n";
        text += "Author: Pierce Martin\n";
        JOptionPane.showMessageDialog(this.getContentPane(), text, "About Chat Log Fixer V" + version, JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_aboutActionPerformed

    //Display a list of the processed files
    private void showProccessedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showProccessedActionPerformed
        // TODO add your handling code here:
        String text = "";
        if (files.size() > 0) {
            for (int i = 0; i < files.size(); i++) {
                File f = (File) files.get(i);
                text += f.getName() + "\n";

            }
        } else {
            text += "No files have been saved.";
        }
        JOptionPane.showMessageDialog(this.getContentPane(), text, "Processed Files", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_showProccessedActionPerformed

    //display help information
    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        try {
            HelpFrame helper = new HelpFrame(this.getContentPane(), new URL(helpURL));//GEN-LAST:event_helpActionPerformed
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(this.getParent(), ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    //show regex matching stats
    private void regexStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regexStatsActionPerformed
        // TODO add your handling code here:
        if (fileLoaded && fileMatched) {
            showStatsTable();
        } else {
            JOptionPane.showMessageDialog(this.getContentPane(), "Mark lines first!");
        }
    }//GEN-LAST:event_regexStatsActionPerformed

    private void addRegexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRegexActionPerformed
        String exp = JOptionPane.showInputDialog(this.getContentPane(), "Enter regular expression to add");
        if (exp != null) {
            checker.addRegex(exp);
        }

    }//GEN-LAST:event_addRegexActionPerformed

private void changeSanitizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSanitizeActionPerformed
    String newSan = JOptionPane.showInputDialog(this.getContentPane(), "Enter new sanitized statement.");
    if (newSan != null) {
        checker.removed = newSan;
        checker.addRegex(newSan);
    }
}//GEN-LAST:event_changeSanitizeActionPerformed

private void undoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoMenuItemActionPerformed
    if (checker.canUndo()) {
        checker.undo();
    }
    undoMenuItem.setEnabled(checker.canUndo());
    redoMenuItem.setEnabled(checker.canRedo());
}//GEN-LAST:event_undoMenuItemActionPerformed

private void redoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoMenuItemActionPerformed
    if (checker.canRedo()) {
        checker.redo();
    }
    undoMenuItem.setEnabled(checker.canUndo());
    redoMenuItem.setEnabled(checker.canRedo());
}//GEN-LAST:event_redoMenuItemActionPerformed

private void editMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuActionPerformed
//GEN-LAST:event_editMenuActionPerformed
    }
private void editMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuMousePressed
}//GEN-LAST:event_editMenuMousePressed

private void menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMousePressed
}//GEN-LAST:event_menuMousePressed

private void regexMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regexMenuMousePressed
}//GEN-LAST:event_regexMenuMousePressed

private void editMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuMouseEntered
    //set whether or not undo and redo can be clicked when user enters menu
    undoMenuItem.setEnabled(checker.canUndo());
    redoMenuItem.setEnabled(checker.canRedo());
}//GEN-LAST:event_editMenuMouseEntered

private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
    //set whether save and marklines menu items can be clicked
    save.setEnabled(fileLoaded);
    markLines.setEnabled(fileLoaded);
}//GEN-LAST:event_menuMouseEntered

private void regexMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regexMenuMouseEntered
    //set whether regexStats can be clicked
    regexStats.setEnabled(fileMatched);
}//GEN-LAST:event_regexMenuMouseEntered

private void previousFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousFileActionPerformed
    // TODO add your handling code here:
    loadPreviousFile();
    updateNextPreviousButtons();
}//GEN-LAST:event_previousFileActionPerformed

private void nextFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFileActionPerformed
    // TODO add your handling code here:
    loadNextFile();
    updateNextPreviousButtons();
}//GEN-LAST:event_nextFileActionPerformed

    //Display a file choosing dialog and return the chosen file
    //Returns null if an invalid file was chosen
    public File loadFile(JFileChooser choose) {
        int returnVal = choose.showOpenDialog(this.getContentPane());

        File f = null;
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            f = new File(choose.getSelectedFile().getAbsolutePath());
        }
        if (f != null && f.canRead()) {
            //JOptionPane.showMessageDialog(choose.getParent(), "You have choosen to open this file: " + choose.getSelectedFile().getName());

            return f;
        } else {
            JOptionPane.showMessageDialog(this.getContentPane(), "Please choose a valid file!", "Invalid File", JOptionPane.ERROR_MESSAGE);
            return null;
        }

    }

    //sets the lable at the top of the window to display the file that is currently being proccessed
    private void setCurrentFileLabel() {
        String fileName = checker.getFile().getName();
        currentFileLabel.setText("Current file: " + fileName);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem addRegex;
    private javax.swing.JButton backButton;
    private javax.swing.JMenuItem changeSanitize;
    private javax.swing.JLabel currentFileLabel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem help;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton insertButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JMenuItem loadFile;
    private javax.swing.JMenuItem loadRegex;
    private javax.swing.JMenuItem markLines;
    private javax.swing.JMenu menu;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nextFile;
    private javax.swing.JButton previousFile;
    private javax.swing.JMenuItem printRegex;
    private javax.swing.JMenuItem quit;
    private javax.swing.JMenuItem redoMenuItem;
    private javax.swing.JMenu regexMenu;
    private javax.swing.JMenuItem regexStats;
    private javax.swing.JButton replaceButton;
    private javax.swing.JMenuItem save;
    private javax.swing.JButton saveButton;
    private javax.swing.JMenuItem showProccessed;
    private javax.swing.JTextPane textPane1;
    private javax.swing.JMenuItem undoMenuItem;
    // End of variables declaration//GEN-END:variables
}
