#!/bin/perl -w

# McD
# --------------------------------------------------------------
# edit_fields: displays the form to edit the fields in a dataset. 
#   Allows the user to edit, add or delete a dataset from the 
#   database.
#
# Expected params:
#   "project" - the project the dataset belongs to
#   "dataset" - (optional) the dataset to edit, if undefined 
#     adding a dataest
#   "mode" - (optional) "add" or "update" mode, default is "add"
#   NOTE: other params are processed by the State module.
#
# Author: Dan Sullivan
# Date: July, 2003
# --------------------------------------------------------------

use strict;
use CGI qw(:standard :html3 );
use lib "lib";
use Utils;
use State;

use lib "../mcd_lib";
use ProjectDBA;
use MLDataset;
use MLDatasetDBA;
use CategoryDBA;

my $proj_dba = ProjectDBA->new();
my $cat_dba = CategoryDBA->new();
my $ds_dba = MLDatasetDBA->new();

my $id = param( "dataset" );
my $project = param( "project" );
my $mode = param( "mode" );
$mode = "add" if( !defined( $mode ) );

my $state = State->new();
$state->setFromParams();
$state = State->new( State::LIST_TABLE, $project ) if( $mode eq "add" );


my $ds = MLDataset->new();
my $proj;

if( defined( $id ) )
{
	$ds = $ds_dba->getFromDB( $id );	
	my @projs = $ds_dba->getProjects( $id );
	$proj = $projs[0]; #------shortcut--------# 
	$project = $proj->{id};
}
else
{
	$id = -1;
	$ds->{date} = today();
	$proj = $proj_dba->getFromDB( $project );
}

println( header( -expires=>'-1d' ) );

println( "<html><head><title>Dataset Edit</title></head>" );
println( $css );
println( $jscript );
println( "<body bgcolor=#e9e9e9 link=white alink=white vlink=white text=black>" );
println( "<center>" );
println( "<form method=post action=proc_update name=\"main_form\">" );
println( $state->getHidden() );
println( "<table border=0 cellpadding=3 cellspacing=8 width=95% bgcolor=#dcdcdc>" );
	println( "<tr bgcolor=#336699><td colspan=2><font color=white size=+1>Edit/Add Dataset</td></tr>" );
	println( "<tr>" );
		println( "<td align=right><b>Project: </b></td>" );
		println( "<td><b>$proj->{name}</b></td>" );
			println( "<input type=hidden name=\"project\" value=\"$project\">" );
	println( "</tr>" );
	println( "<tr>" );
		println( "<td align=right nowrap><b>Date Posted: </b></td>" );
			my @a = split( "-", $ds->{date} );
		println( "<td>" );
			println( "<input type=text size=4 maxlength=4 name=\"year\" value=$a[0]>-".
						 "<input type=text size=2 maxlength=2 name=\"month\" value=$a[1]>-" .
						 "<input type=text size=2 maxlength=2 name=\"day\" value=$a[2]>" );
			println( &nbsp(4), "<a href=\"javascript: today( document.main_form )\"><font size=-1 color=blue>today</a>" );
			println( &nbsp(4), "<a href=\"javascript: blank( document.main_form )\"><font size=-1 color=blue>blank</a>" );
		println( "</td>" );
	println( "</tr>" );
	println( "<tr>" );
		println( "<td align=right nowrap><b>Storm Id: </b></td>" );
		println( "<td>" );
			$ds->{storm_id} = "" if( ! defined( $ds->{storm_id} ) );
			println( "<input type=text size=10 maxlength=15 name=\"storm_id\" value=\"$ds->{storm_id}\">" );	
		println( "</td>" );
	println( "</tr>" );
	println( "<tr>" );
		println( "<td align=right><b>Title: </b></td>" );
		println( "<td><input type=text size=75 name=\"title\" value=\"$ds->{title}\"></td>" );
	println( "</tr>" );
	println( "<tr>" );
		println( "<td align=right><b>Doc URL: </b></td>" );
		println( "<td><input type=text size=75 name=\"doc_url\" value=\"$ds->{doc_url}\"></td>" );
	println( "</tr>" );
	println( "<tr>" );
		println( "<td align=right nowrap><b>Remote URL: </b></td>" );
		my $remote_url = ($ds->{remote_url})? $ds->{remote_url} : "";
		println( "<td><input type=text size=75 name=\"remote_url\" value=\"$remote_url\"></td>" );
	println( "</tr>" );
	println( "<tr>" );
		println( "<td align=right nowrap><b>Status: </b></td>" );
		println( "<td>" );
			println( "<select name=status>" );
				my $selected = "";	
				println( "<option value=none>None</option>" );
					$selected = ( $ds->{status}->{in_progress} )? "selected" : "";
				println( "<option value=in_progress $selected>In Progress</option>" );
					$selected = ( $ds->{status}->{updated} )? "selected" : "";
				println( "<option value=updated $selected>Updated</option>" );
					$selected = ( $ds->{status}->{new} )? "selected" : "";
				println( "<option value=new $selected>New</option>" );
			println( "</select>" );
		println( "</td>" );
	println( "</tr>" );
	println( "<tr>" );
		println( "<td align=right nowrap><b>Hide Dataset: </b></td>" );
		println( "<td>" );
			my $checked = ( $ds->{hide} == 1 )? "checked" : "";
			println( "<input type=checkbox name=\"hide\" $checked>" );
		println( "</td>" );
	println( "</tr>" );
	println( "<tr>" );
		println( "<td colspan=2 align=center bgcolor=#336699><font color=white>&nbsp;</td>" );
	println( "</tr>" );
	if( $mode eq "add" )
	{
		println( "<tr>" );
			println( "<td colspan=2 align=right>" );
				println( "<input type=submit name=\"editButton\" value=\"Next >>\">" );
			println( "</td>" );
		println( "</tr>" );
	}
	println( "<tr>" );
		println( "<td colspan=2 align=right>" );
		println( "<input type=hidden name=\"id\" value=\"$id\">" );
		println( "<input type=hidden name=\"mode\" value=\"$mode\">" );

		if( $mode eq "update" )
		{
			#my $url = $state->getUrl() . "&hlight=$id";
			#my $onClick = "\"return doSubmit( this.value, this.form, top.opener.parent, \'$url\' )\"";
			#println( "<input type=submit name=\"editButton\" value=\"Update\" onClick=$onClick>" );
			#println( "<input type=submit name=\"editButton\" value=\"Add Dataset\">" );
			#println( "<input type=submit name=\"editButton\" value=\"Delete\" onClick=$onClick>" );
			#println( "<input type=submit name=\"editButton\" value=\"Cancel\" onClick=\"return doCancel( this.form, top.opener.parent ) \">" );
			println( "<input type=submit name=\"editButton\" value=\"Update\" >" );
			println( "<input type=submit name=\"editButton\" value=\"Add Dataset\">" );
			println( "<input type=submit name=\"editButton\" value=\"Delete\">" );
			println( "<input type=submit name=\"editButton\" value=\"Cancel\">" );
		}
		else
		{
			println( "<input type=reset name=\"editButton\" value=\"Clear\">" );
			println( "<input type=submit name=\"editButton\" value=\"Cancel\" onClick=\"return doCancel( this.form, top.opener.parent ) \">" );
		}
	println( "</tr>" );

	if( $mode eq "update" )
	{
		println( "<tr>" );
			println( "<td colspan=2 align=right>" );
				println( "<input type=submit name=\"editButton\" value=\"Add/Remove Categories\">" );
			println( "</td>" );
		println( "</tr>" );
		println( "<tr>" );
			println( "<td colspan=2 align=right>" );
				println( "<input type=submit name=\"editButton\" value=\"Edit DLN\">" );
			println( "</td>" );
		println( "</tr>" );
	}
	println( "<tr>" );
		println( "<td colspan=2 align=center bgcolor=#336699><font color=white>&nbsp;</td>" );
	println( "</tr>" );
	
		
println( "</form></table>" );

println( "</body></html>" );

