all:
	f77 -c -I../Commons bd.f bferr.f getval.f bfinfo.f bfsec3.f bfsec4.f ebread.f getobs.f getrec.f lddesc.f nxtbts.f rdhrec.f elmnt.f rdrec.f getnus.f getcfs.f ldtbls.f bfsec0.f bfsec1.f
	ar -rv ../Libs/libeb.a *.o


