Data Type:                         CLASS/Ascending
Project ID:                        DYNAMO
Release Site Type/Site ID:         R/V Sagar Kanya VTJR
Release Location (lon,lat,alt):    999 00.00'E, 99 00.00'N, 999.000, 99.000, 999.0
UTC Release Time (y,m,d,h,m,s):    1987, 05, 05, 23:00:00
Sonde Id/Sonde Type:               E4514351/Vaisala
/
/
/
/
/
Nominal Release Time (y,m,d,h,m,s):1987, 05, 05, 23:00:00
 Time  Press  Temp  Dewpt  RH    Ucmp   Vcmp   spd   dir   Wcmp     Lon     Lat    Ele   Azi   Alt    Qp   Qt   Qrh  Qu   Qv   QdZ
  sec    mb     C     C     %     m/s    m/s   m/s   deg   m/s      deg     deg    deg   deg    m    code code code code code code
------ ------ ----- ----- ----- ------ ------ ----- ----- ----- -------- ------- ----- ----- ------- ---- ---- ---- ---- ---- ----
