#!/bin/perl -w

# --------------------------------------------------------------
# category_table: 
#  Displays datasets by category.  Displays all datasets for 
#  a project or for a single category.
#
# Expected params:
#  "project" - the project id number to display
#  "category" - (optional) the category to display, if no category
#    is given all datasets for the given project are displayed
#  "sleep" - (optional) if defined the script sleeps for one 
#    second, this is used to stall so the proc_update script can
#    update the databse before this page shows the updates in
#    yellow. 
#
# Author: Dan Sullivan
# Date: July, 2003
# --------------------------------------------------------------

use strict;
use CGI qw(:standard :html3 );
use lib "lib";
use Project;
use Utils;
use Category;
use Dataset;
use State;
use Time::HiRes qw(sleep);
#use LTime;
use EQuery;

my $sleep = param( "sleep" );

sleep( 1.00 ) if( $sleep );
#LTime::restart();

my $project = param( "project" );
my $category = param( "category" );

my $hlight = param( "hlight" );
$hlight = -1 if( !defined( $hlight ) );

my @tree;

my $proj = Project->new();
$proj->setFromDB( $project );

my $title = $proj->{title};

my @ptree = Category::getTree( $project );

if( defined( $category ) )
{
	@tree = Category::getSubTree( $category );
}
else
{
	@tree = @ptree;
	$category = -1;
}

my $state = State->new( State::CATEGORY_TABLE, $project, $category );

my $ds = Dataset::getDatasetList( \@tree );

my $count = 0;

println( header( -expires=>'-1d' ) );

println( "<html><head><title>JOSS ML Editor</title></head>" );
println( $css );
println( $jscript );
println( "<body bgcolor=#e9e9e9 link=#000066 alink=#000066 vlink=#000066 text=black>" );
println( "<br><br>" );
println( "<center><table border=0 cellpadding=3 cellspacing=1 width=97%>" );

println( "<tr><td colspan=4 bgcolor=#336699 id=\"path_item\">" );
	println( "<font color=white size=+1><b>Master List: ", &nbsp( 2 ) );
	if( $category != -1 )
	{
		println( "<a href=category_table?project=$project>$proj->{name}</a>&nbsp;&gt;&nbsp;" );
		showPath( \@ptree, $category );
	}
	else
	{
		println( $proj->{name} );
	}
println( "</td></tr>" );

showTable( $ds );

println( "<tr><td colspan=4 bgcolor=#336699><font color=white><b>$count Datasets</td></tr>" );
println( "</table>" );
println( "</body></html>" );

#LTime::log( "$0 project=$project category=$category" );

sub showTable
{
	my $list = shift;
	my $readme = "http://www.joss.ucar.edu/master_list/readme.gif";

	if( $list )
	{
		my @list = @$list;
		foreach my $node (@list)
		{
			if( $category != $node->{category}->{id} )
			{
				println( "<tr>" );
					println( "<td bgcolor=#e9e9e9>&nbsp;</td>" );
					println( "<td colspan=3 bgcolor=#dcdcdc><b>$node->{category}->{name}</td>" );
				println( "</tr>" );
			}
			
			foreach my $ds ( @{$node->{datasets}} )
			{
				$count++;
				my $bgcolor = ( $ds->{hide} == 1 )? "#999999" : "white";
				$bgcolor = ( $ds->{id} == $hlight )? "#FFFFCC" : $bgcolor;
				
				println( "<tr bgcolor=$bgcolor onmouseover=\"javascript: style.backgroundColor=\'#ebebf5\'\" onmouseout=\"javascript: style.backgroundColor=\'$bgcolor\'\">" );
				#println( "<tr bgcolor=$bgcolor>" );

					my $url = "edit_fields?mode=update&dataset=$ds->{id}";
					$url = $url . $state->getUrlParams();

					println( "<td bgcolor=#e9e9e9 width=5% id=\"edit_link\" align=center>", 
									 "<a href=\"javascript: editWindow( \'$url\' )\">",
									 "<font size=-2>EDIT</a></font></td>" );
					println( "<td width=75% id=\"listing_link\">" );
						if( defined( $ds->{url} ) && $ds->{url} ne "" )
						{
							println( "<a href=$ds->{url} target=_blank>$ds->{title}</a>" );
						}
						else
						{
							println( "$ds->{title}" );
						}

					println( "</td>" );


					println( "<td nowrap align=center width=10%>" );
						if( $ds->{in_progress} == 1 )
						{ println( "<font color=red>In Progress</font>" ); }
						elsif( $ds->{date} ne "0000-00-00" )
						{ println( "$ds->{date}" ); }
						else
						{ println( "&nbsp;" ); }
					println( "</td>" );

					println( "<td nowrap align=center id=\"listing_link\" width=10%>" );
						if( defined( $ds->{doc_url} ) && $ds->{doc_url} ne "" )
						{
							println( "<a href=$ds->{doc_url} target=_blank><font size=-1>documentation</a>" );
						}
						elsif( defined( $ds->{storm_id} ) && $ds->{storm_id} ne "" && $ds->{storm_id} ne "99.999" )
						{
							my $eq = EQuery->new( "catalog_db" );
							$eq->query( "SELECT dir_path, file_name FROM dataset WHERE storm_id=" . $eq->quote( $ds->{storm_id} ) );
							my %row = $eq->getRow();
							if( %row )
							{
								if( $row{dir_path} ne "" & $row{file_name} ne "" )
								{
									my $url = 	"http://www.joss.ucar.edu" .
															substr( $row{dir_path}, length( "/web" ) ) .
															"/$row{file_name}";	
									println( "<a href=$url><font size=-1>documentation</a>" );
								}
							}
							#println( "&nbsp;" );
						}
						else
						{
							println( "&nbsp;" );
						}
					println( "</td>" );
				println( "</tr>" );
			}

			showTable( $node->{childern} ); 
		}
	}
}

sub showPath
{
	my @tree = @{ $_[0] };
	my $cat = $_[1];

	foreach my $node ( @tree )
	{
		if( $node->{category}->{id} == $category )
		{
			println( $node->{category}->{name} );
			return;
		}
		elsif( $node->inTree( $category ) )
		{
			println( "<a href=category_table?project=$project&category=$node->{category}->{id}>$node->{category}->{name}</a>&nbsp;&gt;&nbsp;" );
			showPath( $node->{childern}, $category );
			last;
		}
	}
}
