#******************************************************************
# WrapperLinkSearch.pl 
# Wrapper Script calling linkSearch.pl, a program that will identify the status of the URL segments on
# EMDAC Master Lists.
#
# linkSearch.pl was written by A. Robinson (NCAR/EOL/DMS)
# linkSearch.pl original location: /net/work/software/tools/link_verification/linkSearch.pl
#
# @@author Alley Robinson
# @@date July 18, 2018
#
# INPUT: 
#	listofprojects_[startyear]_[endyear].txt - contains the list of project names to be processed.
#		THESE NAMES MUST BE IN LOWER CASE (i.e epic)
#
# OUTPUT:
# 	2 files generated by linkSearch.pl 
#
# HOW TO RUN:
# 	perl WrapperLinkSearch.pl [input_file_name] > [LOG_NAME_.log]
# 	Example: perl WrapperLinkChecker.pl /net/work/software/tools/link_verification/celeste_tool/input/listofprojects_2000_2004.txt >& FULL_OUTPUT_2000_2004.log
#
#******************************************************************
use strict;
use warnings;

printf "Welcome! WrapperLinkSearch.pl  began on ";print scalar localtime;printf "\n";

# Declare Global Variables
my $debug = 0;

parseList();

printf "See you later! WrapperLinkSearch.pl  ended on ";print scalar localtime;printf "\n";



#*************************************
# parseList() 
# This function will parse the project list 
# and call the linkSearch.pl script.
#
#*************************************
sub parseList
{
	my $linkSearch = "./linkSearch.pl";

        unless (-e $linkSearch)
        {
                die "ERROR: linkSearch.pl does not exist. Please put code in this working directory. \n";
        }


	# The input will be a list of projects
	my $projectList = $ARGV[0];
	print "Input File: $projectList \n";

	# Opening input file and sorting lines/projects into an array
	open (my $inputFile, '<', $projectList) or die "Cannot open the $projectList: $! \n";

	my @lines = <$inputFile>;
	print "Project(s) to be processed: \n @lines \n";

	# Begin Looping
	print "Begin processing linkSearch.pl \n";

	foreach my $project (@lines)
	{
		$project =~ s/^\s+|\s+$//g;
		print "---------------------------------Processing Project: $project---------------------------------\n";
		system("/bin/perl linkSearch.pl $project");
		print "\n";
	}

}

