#! /bin/perl -w
# WrapperLinkChecker.pl
#
# Title: WrapperLinkChecker.pl - a wrapper script calling linkChecker.pl, a program that identifies broken links on EMDAC Master Lists.
#   -- linkChecker.pl was written by A. Robinson (NCAR/EOL/DMS). 
#   -- linkChecker.pl original location: /net/work/software/tools/link_verification/linkChecker.pl
#   -- Please see linkChecker.pl for more information on the utilities of the script.
#
# Author: Celeste Connell (NCAR/EOL/DMS)
# 
# Date created: 09 July 2018
# Last updated: 27 July 2018
# 
# Input:  listofprojects_[startyear]_[endyear].txt - contains the list of project names to be processed.
#         THE NAMES IN THAT FILE MUST BE LOWERCASE. (E.g. epic, pecan, etc.)
#
# Outputs: 6 output files generated by linkChecker.pl, and
#          new log file indicated by user in the command line [LOG_NAME_.log]
#          
# Execute: perl WrapperLinkChecker.pl [input_file_name] >& [LOG_NAME_.log]
# Example: perl WrapperLinkChecker.pl /net/work/software/tools/link_verification/celeste_tool/input/listofprojects_2000_2004.txt >& FULL_OUTPUT_2000_2004.log
#
# Description:
#   This wrapper script will read the names of the projects from the input file specified by the user,
#   and process each project in the order shown in the input file.
#   When linkChecker.pl runs, it generates several output files, each of which will have the project name specified in the output file names.
#   Additionally, the >& in the command line followed by a [LOG_NAME_.log] will create a new processing log file.
#
# **********************************************************************************************************************************************************

use strict;
use warnings;

print "\nHello! WrapperLinkChecker.pl began on "; print scalar localtime . ".\n\n";

sub WrapperLinkChecker
{
  #assigning variables to user-specified file
  my $projectlist = $ARGV[0];
  print "Input file: $projectlist\n\n";

	#opening input file and sorting lines/projects into an array
  open (my $inputfile, '<', $projectlist) or die "Cannot open file $projectlist: $!";
  my @lines = <$inputfile>;
  print "Project(s) to be processed: \n @lines \n";
  close($inputfile);

  #Begin loop.
  print "\nBegin loop with linkChecker.pl\n";
  foreach my $project (@lines) {
    $project =~ s/^\s+|\s+$//g;
    print "---------------------------------Processing Project: $project---------------------------------\n";
    system ("/bin/perl linkChecker.pl $project");
    print "\n";
    }  #end loop
  
  print"\n";
	print "WrapperLinkChecker.pl completed on "; print scalar localtime . ".\n\n";

}	#end sub WrapperLinkChecker
	
	
WrapperLinkChecker();		#runs the above subroutine

