#!/bin/perl -w

# --------------------------------------------------------------
# codiac_readme:
#   Obtains the readme file_name and dir_path from CODIAC for
#    the given storm_id and forwards the user to the page
#   If no file_name or dir_path are found the user is given
#    a 'no documentation' found message.
#
# Expected Params:
#   "storm_id" - the storm_id to query from CODIAC.
#
# Author: Dan Sullivan
# Date: July, 2003
# --------------------------------------------------------------

use lib "../lib";
use strict;
use EQuery;
use CGI;
use Utils;

my $cgi = CGI->new();
my $storm_id = $cgi->param( "storm_id" );

my $eq = EQuery->new( "catalog_db" );
$eq->query( "SELECT dir_path, file_name FROM dataset WHERE storm_id=" . $eq->quote( $storm_id ) );

my %row = $eq->getRow();
my $url;
if( %row )
{
	if( $row{dir_path} ne "" & $row{file_name} ne "" )
	{
		$url = 	"http://www.joss.ucar.edu" .  substr( $row{dir_path}, length( "/web" ) ) .
						"/$row{file_name}";	
	}
}

if( $url ne "" )
{
	print( "Location: $url\n\n" );
	exit 0;
}
else
{
	println( $cgi->header() );
	println( "<html><head><title>JOSS Documentation Not found</title></head>" );
	println( "<body bgcolor=white text=black>" );
	println( "<center><br><br><br>" );
	println( "<b><font size=+2 face=Verdana>Sorry, no documentation found for this dataset.</font></b>" );
	println( "</body></html>" );
}

