#!/bin/perl -wT

# --------------------------------------------------------------
# category_table: 
#  Displays datasets by category.  Displays all datasets for 
#  a project or for a single category.
#
# Expected params:
#  "project" - the project id number to display
#  "category" - (optional) the category to display, if no category
#    is given all datasets for the given project are displayed
#
# Author: Dan Sullivan
# Date: July, 2003
# --------------------------------------------------------------

use strict;
use CGI;
use lib "../lib";
use Project;
use Utils;
use Category;
use Dataset;
use Link;
use EQuery;
require( "./show_error" );

$CGI::POST_MAX = 1024;
$CGI::DISABLE_UPLOADS = 1;

my $cgi = CGI->new();
my $project = $cgi->param( "project" );
$project = 1;
#my $category = $cgi->param( "category" );
my $category;
my @tree;
#check_valid( $project, $category );

my $proj = Project->new();
$proj->setFromDB( $project );

my $title = $proj->{name};

my @ptree = Category::getTree( $project );

my $ds = Dataset::getDatasetList( \@ptree, 0  );

my $count = 0;

println( $cgi->header() );

println( "<html><head><title>JOSS Master List</title>" );
#println( &body_css( $proj->{body_css_src}) );
println( $jscript );
println( "<head>" );
println( "<body>" );
#println( "<body bgcolor=#e9e9e9 link=#000066 alink=#000066 vlink=#000066 text=black>" );
#println( "<center><font size=+3 color=blue face=Verdana><b>$proj->{name} Data Sets</font></b>" );
#println( &nbsp(2), "<img src=http://www.joss.ucar.edu/master_list/images/joss.gif>" );
println( "<br>" );


println( "<table border=0 cellpadding=4 cellspacing=0 width=100% height=100%>" );

	printLayers( \@ptree, 0, 0 )

println( "</table>" );

println( "</body></html>" );

sub printLayers
{
	my $tree = shift;
	my $depth = shift;
	my $count = shift;
	my $tcount = $count;

	if( $tree )
	{
		foreach my $node (@$tree)
		{
			println( "<div id='layer_${depth}_${count}'>" );
			
				println( "<tr>" );
					println( "<td width=20%>" );
						printLeftLayer( \@ptree, $depth, $count );
					println( "</td>" );
					println( "<td width=20%>" );
						#printRightLayer( \@ptree, $depth, $count );
					println( "</td>" );
				println( "</tr>" );	
			println( "</div>" );
		}
	}
}

sub printLeftLayer
{
	my $tree = shift;
	my $depth = shift;
	my $count = shift;
	my $tcount = $count;
	my $ccount = 0;

	if( $depth > 0 )
	{
		foreach my $node (@$tree)
		{
			println( "<tr>" );
				println( "<td>", &nbsp($depth*2) );
					my $nd = $depth+1;
					my $href = "javascript: showLayer(0, 'layer_${nd}_${ccount}')";

					println( "<a href=\"$href\">$node->{category}->{name}</a>" );	
				println( "<br>" );
				println( "</td>" );
			println( "</tr>" );

			printLeftLayers( $node->{childern}, $depth+1, $count );
		}

		println( "</div>" );
	}		
}

sub printRightLayers
{
println( "<center><table border=0 cellpadding=4 cellspacing=0 width=97% bgcolor=#dcdcdc class=titleTable>" );
	println( "<tr>" );
		println( "<td align=center valign=center width=15%>" );
			println( "&nbsp;" );
		println( "</td>" );
		println( "<td align=center valign=top width=70%>" );
			println( "$proj->{name} Data Sets<br>" );
			println( "<font size=-1><i>$proj->{long_name}</i></font>" );
		println( "</td>" );
		println( "<td align=center valign=center width=15%>" );
			println( &nbsp(2), "<img src=http://www.joss.ucar.edu/master_list/images/joss.gif>" );
		println( "</td>" );
	println( "</tr>" );
println( "</table>" );
println( "<br>" );
println( "<center><table border=0 cellpadding=3 cellspacing=1 width=97%>" );

	println( "<tr bgcolor=#336699 class=tableHead><td colspan=4>" );
		println( "$proj->{name} Master Data Set List" );
		if( $category != -1 )
		{
			println( ": <a href=category_table?project=$project>All</a>&nbsp;&gt&nbsp;" );
			showPath( \@ptree, $category );
		}
	println( "</td></tr>" );

showTable( $ds );

my $total = "Total Number of <i>$proj->{name}</i> Data Sets: $count";
$total = "Total Number of <i>$tree[0]->{category}->{name} </i> Data Sets: $count" if( $category != -1 );
 
println( "<tr bgcolor=#336699 class=tableHead><td colspan=4>$total</td></tr>" );
println( "</table>" );
}

sub showTable
{
	my $list = shift;
	my $readme = "http://www.joss.ucar.edu/master_list/readme.gif";

	if( $list )
	{
		my @list = @$list;
		foreach my $node (@list)
		{
			my @links = Link::getCategoryLinks( $node->{category}->{id} );

			#if( $category != $node->{category}->{id} )
			#{
				println( "<tr bgcolor=#dcdcdc class=catHead>" );
					println( "<td colspan=3><b>$node->{category}->{name}</b>" );
					foreach my $link (@links)
					{
						println( &nbsp(3), "<a href=$link->{url} target=$link->{target}>$link->{name}</a>" );
					}
				println( "</tr>" );
			#}
			
			foreach my $ds ( @{$node->{datasets}} )
			{
				$count++;
				
				println( "<tr bgcolor=white onmouseover=\"javascript: style.backgroundColor=\'#ebebf5\'\" onmouseout=\"javascript: style.backgroundColor=\'white\'\">" );

					println( "<td width=75% class=dsTitleCell>" );
						if( defined( $ds->{url} ) && $ds->{url} ne "" )
						{
							if( $ds->{url} =~ /^ftp/ )
							{
								println( "<a href=ftp_url?dataset=$ds->{id} target=_top>$ds->{title}</a>" );
							}
							else
							{
								println( "<a href=$ds->{url} target=_top>$ds->{title}</a>" );
							}

						}
						else
						{
							println( "$ds->{title}" );
						}

					println( "</td>" );


					println( "<td nowrap align=center width=10%>" );
						if( $ds->{in_progress} == 1 )
						{ println( "<font color=red>In Progress</font>" ); }
						elsif( $ds->{date} ne "0000-00-00" )
						{ println( "$ds->{date}" ); }
						else
						{ println( "&nbsp;" ); }
					println( "</td>" );

					println( "<td nowrap align=center class=dsDocCell width=10%>" );
						if( defined( $ds->{doc_url} ) && $ds->{doc_url} ne "" )
						{
							println( "<a href=$ds->{doc_url}>documentation</a>" );
							#println( "<a href=$ds->{doc_url}><font size=-1>" );
							#println( "<img src=http://www.joss.ucar.edu/master_list/images/readme.gif border=0>" );
						}
						elsif( defined( $ds->{storm_id} ) && $ds->{storm_id} ne '' && $ds->{storm_id} ne "99.999" )
						{
							my $eq = EQuery->new( "catalog_db" );
							$eq->query( "SELECT dir_path, file_name FROM dataset WHERE storm_id=" . $eq->quote( $ds->{storm_id} ) );
							my %row = $eq->getRow();
							if( %row )
							{
								if( $row{dir_path} ne "" & $row{file_name} ne "" )
								{
									my $url = 	"http://www.joss.ucar.edu" .
															substr( $row{dir_path}, length( "/web" ) ) .
															"/$row{file_name}";	
									println( "<a href=$url>documentation</a>" );
								}
							}
							#my $url = "codiac_readme?storm_id=$ds->{storm_id}";
							#println( "<a href=$url>documentation</a>" );
						}
						else
						{
							println( "&nbsp;" );
						}
					println( "</td>" );
				println( "</tr>" );
			}

			showTable( $node->{childern} ); 
		}
	}
}

sub showPath
{
	my @tree = @{ $_[0] };
	my $cat = $_[1];

	foreach my $node ( @tree )
	{
		if( $node->{category}->{id} == $category )
		{
			println( $node->{category}->{name} );
			return;
		}
		elsif( $node->inTree( $category ) )
		{
			println( "<a href=category_table?project=$project&category=$node->{category}->{id}>$node->{category}->{name}</a>&nbsp;&gt;&nbsp;" );
			showPath( $node->{childern}, $category );
			last;
		}
	}
}
sub check_valid
{
	my $project = shift;
	my $category = shift;

	if( !defined( $project ) ) 
	{
		show_error( "category_table: undefined project id." );
	}
	elsif( $project =~ /\D/ )
	{
		show_error( "category_table: project id not valid: $project" );
	} 
	elsif( defined( $category ) && $category =~ /\D/ )
	{
		show_error( "category_table: category id not valid: $category" );
	} 
}
