#!/bin/perl -w

# --------------------------------------------------------------
# proc_update - processe the form from the proc_fields form
#  Performs the needed database operations on the dataset and
#  then displays a status message or allows the user to edit
#  the dataset-category links.
#
# Expected Params:
#   "editButton" - the button the user clicked, used to 
#    determine the action.
#  Others from the form, see the getPostedDs() subroutine.
#
# Author: Dan Sullivan
# Date: July, 2003
# --------------------------------------------------------------

use strict;
use CGI qw(:standard :html3 );
use lib "lib";
use Dataset;
use Utils;
use MLDB;
use State;
#use Time::HiRes qw(sleep);
#use LTime;

require "./edit_ds_cats";

my %actions = ( "Next >>" => \&editCats, 
								"Add/Remove Categories" => \&editCats, 
								"Done" => \&updateCats, 
								"Update" => \&updateDs, 
								"Add Dataset" => \&addDs, 
								"Delete" => \&deleteDs, 
								"Cancel" => \&cancelDs );

my $action = param( "editButton" );

my $ds = getPostedDs(); 
my $state = State->new();
$state->setFromParams();

$actions{$action}->();

#LTime::log( "$0 action=$action" );

sub showPage
{
	my $msg = shift;

	println( header() );

	println( "<html><head><title>Dataset Edit</title></head>" );
	println( $css );
	println( $jscript );

	println( "<body bgcolor=#e9e9e9 link=white alink=white vlink=white text=black>" );
	println( "<center><table border=0 cellpadding=3 cellspacing=8 width=95% bgcolor=#e9e9e9>" );
		println( "<tr bgcolor=#336699><td><font color=white size=+1>Edit/Add Dataset</td></tr>" );
		println( "<tr><td>&nbsp;</td></tr>" );
		println( "<tr><td>&nbsp;</td></tr>" );
		println( "<tr><td align=center><b>$msg</b></td></tr>" );
		println( "<tr><td align=center><input type=submit value=\"Close Window\" onClick=\"window.close();\"></td></tr>" );
		println( "<tr><td>&nbsp;</td></tr>" );
		println( "<tr><td>&nbsp;</td></tr>" );

	println( "</body></html>" );
}

sub forward
{
	my $page = shift;
	print( "Location: $page\n\n" );

	exit 0;
}

sub updateDs
{
	$ds->updateDB();

	showPage( "Dataset has been updated." );
}

sub addDs
{
	$ds->{id} = -1;

	editCats();
}

sub deleteDs
{
	$ds->deleteDB();

	showPage( "Dataset has been deleted." );
}

sub cancelDs
{
	$ds->{id} = -1;

	showPage( "Action Canceled" );
}

sub editCats
{
	my $mode = "update";

	if( $ds->{id} == -1 )
	{
		$ds->insertDB();	
		$mode = "add";
	}
	else
	{
		$ds->updateDB();
	}

	edit_ds_cats( $ds, $mode );
}

sub getPostedDs
{
	my $ds = Dataset->new();

	$ds->{id} = param( "id" );
	$ds->{title} = param( "title" );
	$ds->{storm_id} = param( "storm_id" );

	my $year = param( "year" );
	my $month = param( "month" );
	my $day = param( "day" );
	if( defined( $year ) && defined( $month ) && defined( $day ) )
	{	
		$ds->{date} = param( "year" ) . "-" . param( "month" ) . "-" . param( "day" );	
	}
	else
	{
		$ds->{date} = undef();
	}
	$ds->{url} = param( "url" );
	$ds->{doc_url} = param( "doc_url" );
	$ds->{in_progress} = ( defined( &param( "in_progress" ) ) )? 1: 0;
	$ds->{hide} = ( defined( &param( "hide" ) ) )? 1: 0;
	$ds->{project} = param( "project" );

	$ds->checkDefined();

	return $ds;
}

sub updateCats
{
	my @cats = param( "category" );

	if( @cats )
	{
		$ds->updateCategories( \@cats );
	}
	else
	{
		$ds->updateCategories();
	}

	my $mode = param( "mode" );
	my $msg = "Dataset has been updated.";
	if( defined( $mode ) && $mode eq "add" )
	{
		$msg = "Dataset has been added."
	}
	
	showPage( $msg );
}

