package dts.port;

import java.sql.*;
import java.util.*;

/**
 * The DatasetSource class is a container that connects a processed data set with a source
 * Dataset.
 * 
 * @author jclawson
 */
public class DatasetSource {

	private Boolean excluded;
	private Dataset dataset, source;
	
	/**
	 * Create a new instance of a DatasetSource.
	 * @param dataset The parent data set.
	 * @param source The source data set for the parent.
	 */
	public DatasetSource(Dataset dataset, Dataset source) {
		this.dataset = dataset;
		this.source = source;
	}
	
	/**
	 * Get the parent data set.
	 * @return The parent Dataset.
	 */
	public Dataset getDataset() { return dataset; }
	
	/**
	 * Get the source data set for the pair.
	 * @return The source Dataset.
	 */
	public Dataset getSource() { return source; }
	
	/**
	 * Determine if the source data set is excluded from the generation of the parent data set.
	 * @return <code>true</code> if this source is excluded from the parent data set, <code>false</code>
	 * if it is not.
	 */
	public boolean isExcluded() {
		return excluded == null ? false : excluded.booleanValue();
	}
	
	/**
	 * Set the flag that marks this source as excluded from the parent data set..
	 * @param flag The excluded flag.
	 * @throws MergeException if the flag does not match a previously set value.
	 */
	public void setExcluded(boolean flag) throws MergeException {
		// Set the flag for the first time.
		if (excluded == null) { excluded = new Boolean(flag); }
		// Make sure the flag matches a previously set value.
		else if (flag != excluded.booleanValue()) {
			throw new MergeException("Dataset "+getDataset().getDatasetId()+" has a mismatched exclude flag for source data set "+getSource().getDatasetId());
		}
	}
	
	/**
	 * Insert the associations between a processed data set and its source data set(s).
	 * @param porter The class controlling the database porting.
	 * @param connection The connection to the DTS database.
	 * @param datasets The mapping of data sets in the DTS.
	 * @return <code>true</code> if the source data sets were associated successfully, <code>false</code>
	 * if there is at least one problem.
	 * @throws SQLException if there is a problem executing the statements.
	 */
	public static boolean storeDataTrackingSystemSourceDatasets(ToDmgDts porter, Connection connection, Map datasets, Map users) throws SQLException {
		// Define the success flag to mark if there were any errors during the insert.
		boolean success = true;
		// Define the statement to insert a source data set as a potential source data set.  Note the
		// ON DUPLICATE KEY part of the statement.  Since a data set may be a source to multiple data sets,
		// this will ensure any new source is added without modifying an existing entry.
		PreparedStatement infoStmt = connection.prepareStatement("INSERT INTO dataset_source_info(dataset_id, collection_time_note_id, source_info_note_id) VALUES(?, ?, ?) ON DUPLICATE KEY UPDATE dataset_id=dataset_id");
		// Define the SQL to insert the source data set into the database.
		String sql = "INSERT INTO dataset_source_dataset(dataset_id, source_dataset_id, exclude_flag) VALUES(?, ?, ?)";
		// Define the statement that will execute the insert query.
		PreparedStatement stmt = connection.prepareStatement(sql);
		
		// Define an iterator over all of the data sets since there isn't a set of known data sets that have a source data set.
		Iterator datasetItr = datasets.values().iterator();
		// Loop through the data sets in the iterator.
		while (datasetItr.hasNext()) {
			// Extract the current data set from the iterator.
			Dataset dataset = (Dataset)datasetItr.next();
			
			// Only worry about data sets that have sources.
			if (dataset.getSourceDatasets().size() > 0) {
				try { 
					// Apply the data set to the insert statement.
					stmt.setString(1, dataset.getDatasetId());
					
					// Define the iterator over the source data sets.
					Iterator srcItr = dataset.getSourceDatasets().iterator();
					// Loop through each source data set.
					while (srcItr.hasNext()) {
						// Extract the source data set information from the iterator.
						DatasetSource source = (DatasetSource)srcItr.next();
	
						try {
							Note collectionTimeNote = new Note((User)users.get("local"), new Timestamp(new java.util.Date().getTime()), "<p>This is a place holder generated by the porting of the DTS database.</p>");
							collectionTimeNote.storeInDataTrackingSystem(connection);
							Note sourceInfoNote = new Note((User)users.get("local"), new Timestamp(new java.util.Date().getTime()), "<p>This is a place holder generated by the porting of the DTS database.</p>");
							sourceInfoNote.storeInDataTrackingSystem(connection);
							
							// Assign the source to source info statement and execute.
							infoStmt.setString(1, source.getSource().getDatasetId());
							infoStmt.setInt(2, collectionTimeNote.getId());
							infoStmt.setInt(3, sourceInfoNote.getId());
							infoStmt.execute();
						
							// Only continue with association if the source was added to the info table.
							try { 
								// Assign the source to the data set association and execute.
								stmt.setString(2, source.getSource().getDatasetId());
								stmt.setBoolean(3, source.isExcluded());					
								stmt.execute();
							}
							// Handle problems with the data set <-> source association.
							catch (SQLException e) {
								success = false;
								porter.appendMergeException(new MergeException("Dataset "+dataset.getDatasetId()+" could not be linked source data set "+source.getSource().getDatasetId()+"  "+e.getMessage()));
							}
						} 
						// Handle problems with inserting a source into the source info table.
						catch (SQLException e) {
							success = false;
							porter.appendMergeException(new MergeException("Source Dataset "+source.getSource().getDatasetId()+" could not be inserted into the source info table.  "+e.getMessage()));
						}
					}					
				}
				// Handle any other exception for the parent data set.
				catch (SQLException e) {
					success = false;
					porter.appendMergeException(new MergeException("Dataset "+dataset.getDatasetId()+" could not be attached to a source data set.  "+e.getMessage()));
				}
			}			
		}
		
		// Properly close the open statement stream.
		try { stmt.close(); } catch (SQLException e) {}
		try { infoStmt.close(); } catch (SQLException e) {}
		
		// Return the success status of all of the insert statements.
		return success;
	}
}
