#!/bin/perl

#-----------------------------------------------------
# platforms: a simple cgi script to display all of the
#  entries in the storm_id_project table in the catalog_db
#  database.
#
# Author: Dan Sullivan
# Date: April 24, 2003
#-----------------------------------------------------

use CGI qw(:standard :html3 );

getProjectId();

sub getProjectId
{
	my $db_path = "/storm/codiac/codiac_db";
	my $empcmd = "/usr/empress8.20/rdbms/bin/empcmd";
	$ENV{MSPATH} = "/usr/empress8.20/rdbms";
	$ENV{MSQLSELCOLSEP} = "";

	my $sort = param( "sort" );
	my $sql = "";

	if( defined( $sort ) )
	{
		$sql = "\"SELECT * FROM storm_id_project ORDER BY '$sort'\"";
	}
	else
	{
		$sql = "\"SELECT * FROM storm_id_project\"";
	}

	@records = `$empcmd $db_path/catalog_db $sql`;

	println( header() );
	println( "<html><head><title>QUERY CODIAC: Project Id Numbers</title></head><body bgcolor=white>" );
	println( "<center><h3>QUERY CODIAC: Project Id Numbers</h3>" );

	println( "<table border=1 cellpadding=1 cellspacing=1>" );
	println( "<tr>" );
		println( "<th><a href=projectId?sort=storm_id>Prefix/Id</a></th>" );
		println( "<th><a href=projectId?sort=project_id>Project</a></th>" );
	println( "</tr>" );

	for( my $x = 2; $x < @records; $x++ )
	{
		my @id = split( //, $records[$x] );
		println( "<tr>" );
			println( "<td>$id[0]</td>" );
			println( "<td>$id[1]</td>" );
		println( "</tr>" );
	}
	println( "</table>" );

	println( "</body></html>" );	
}

sub println
{
	print( @_, "\n" );
}
