/*
 * TextScrollPane.java
 *
 * Created on May 15, 2008, 10:23 AM
 */
package chatscrubber;

import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  pmartin
 */
public class TextScrollPane extends javax.swing.JFrame {

    String text;

     //Container location is used to set where the frame is generated on the screeen
    //location is also used to set size of help frame
    public TextScrollPane(Container location, String textToPrint) {
        text = textToPrint;
        init(location);
        setText(text);
    }

    public TextScrollPane(Container location) {
        init(location);
    }

    private void init(Container location) {
        initComponents();
        //set to dispose instead of killing whole application
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        //resize frame
        int sizeX = location.getWidth() / 2;
        int sizeY = 3 * location.getHeight() / 4;

        this.setSize(sizeX, sizeY);

        //center frame on location container
        this.setLocationRelativeTo(location);

        setVisible(true);
    }
    private void setText(String txt) {
        try {
            jEditorPane1.setText(txt);
            //set position to beginning of text
            jEditorPane1.setEditable(true);
            jEditorPane1.setCaretPosition(0);
            jEditorPane1.setEditable(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.getParent(), ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JEditorPane jEditorPane1;
    protected javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
