#! /usr/bin/perl -w

package AddProductEditorCGI;
use strict;
use lib "..";
use EditorCGI;
our @ISA = ("EditorCGI");

&main();

sub main {
    my $self = AddProductEditorCGI->new();
    $self->buildPage("Add Product: ".$self->getProject()->getId());
}

sub buildPageBody {
    my ($self) = @_;

    printf("<form action=\"product_action\" method=\"POST\" onSubmit=\"javascript: return validateProduct(this);\">\n");
    printf("   <input type=hidden name=project value=\"%s\" />\n",$self->getProject()->getId());
    printf("   <table class=editTable>\n");
    printf("      <tr class=editHeading><td colspan=2>Add Product</td></tr>\n");
    printf("      <tr>\n");
    printf("         <th>Project:</th>\n");
    printf("         <td>%s</td>\n",$self->getProject()->getId());
    printf("      </tr>\n");
    printf("      <tr>\n");
    printf("         <th>Type:</th>\n");
    printf("         <td>\n");
    printf("            <select name=type onChange=\"javascript: changeProductType(this);\">\n");
    printf("               <option value=\"Composite\" selected>Composite</option>\n");
    printf("               <option value=\"Group\">Group</option>\n");
    printf("            </select>\n");
    printf("         </td>\n");
    printf("      </tr>\n");
    printf("      <tr><td class=editSpacer colspan=2></td></tr>\n");
    printf("      <tr id=CompositeId style=\"display: table-row;\">\n");
    printf("         <th>Dataset Id:</th>\n");
    printf("         <td><input type=text name=\"dataset_id\" size=15 maxsize=15 /></td>\n");
    printf("      </tr>\n");
    printf("      <tr id=CompositeName style=\"display: table-row;\">\n");
    printf("         <th>Dataset Name:</th>\n");
    printf("         <td><input type=text name=\"dataset_name\" size=70 maxsize=255 /></td>\n");
    printf("      </tr>\n");
    printf("      <tr id=GroupName style=\"display: none;\">\n");
    printf("         <th>Group Name:</th>\n");
    printf("         <td><input type=text name=\"group_name\" size=70 maxsize=255 /></td>\n");
    printf("      </tr>\n");
    printf("      <tr><td class=editSpacer colspan=2></td></tr>\n");
    printf("      <tr>\n");
    printf("         <th>Status:</th>\n");
    printf("         <td>\n");
    printf("            <select name=\"status\">\n");
    $self->printStatusOptions();
    printf("            </select>\n");
    printf("         </td>\n");
    printf("      </tr>\n");
    printf("      <tr>\n");
    printf("         <th>Notes:</th>\n");
    printf("         <td><textarea name=note_text rows=20 cols=70></textarea></td>\n");
    printf("      </tr>\n");
    printf("      <tr><td class=editSpacer colspan=2></td></tr>\n");
    $self->printButtonRow("Add",2);
    printf("   </table>\n");
    printf("</form>\n");
}
