#! /usr/bin/perl -w

##Module------------------------------------------------------------------------------------
# The NcepArchive module is used for archiving the ingested data from NCEP and preparing
# it for making it available on CODIAC.
#
# @author Joel Clawson
##Module------------------------------------------------------------------------------------
package NcepArchive;
use strict;
use Cwd;
use File::Copy;
use NcepUtil;

my $LOG;

##-------------------------------------------------------------------------------------------
# @signature String archive_ceopavn()
# <p>Tar the <code>ceopavn</code> files into a tar ball that will eventually be put on the 
# mass store.</p>
#
# @output $err The error message generated by creating the tar ball, or an empty string
# if there are no errors to report.
##-------------------------------------------------------------------------------------------
sub archive_ceopavn {
    my $self = shift;
    my $ingest = sprintf("%s/ingest/%04d/%02d/ceopavn",NcepUtil::ncep_home(),$self->{"year"},
			 $self->{"month"});

    if (-e $ingest) {
	# Go to the directory where the files can be found
	my $cur_dir = cwd();
	chdir($ingest) or return "Unable to change to $ingest.";
	printf($LOG "Changed to %s.\n",$ingest);

	# Define the archive information
	my $archive = sprintf("%s/archive/%04d",NcepUtil::ncep_home(),$self->{"year"});
	my $file = sprintf("ceopavn.%04d%02d.tar",$self->{"year"},$self->{"month"});

	# Create the archive directory
	unless (-e $archive) {
	  NcepUtil::create_directory($archive);
	    printf($LOG "Created directory: %s\n",$archive);
	}

	# Remove the current tar ball so it can be overwritten
	if (-e sprintf("%s/%s",$archive,$file)) {
	    printf($LOG "$file already exists.  Deleting and remaking.\n");
	    unlink(sprintf("%s/%s",$archive,$file));
	}
	
	# Create the tar ball of the ceopavn data
	if (NcepUtil::tar(sprintf("%s/%s",$archive,$file),"ceop*") == 0) {
	    printf($LOG "Created ceopavn tar file: %s",$file);
	    
	    # Since the tar file is created, this is no longer needed.
	    unlink(glob(sprintf("%s/ceop*",$ingest))) or 
		return "Unable to remove ceopavn files.";
	    printf($LOG "Removed the ceopavn files\n");

	    # Return to the original working directory
	    chdir($cur_dir) or return "Unable to return to $cur_dir.";
	    printf($LOG "Changed to %s directory\n",$cur_dir);

	    # Remove the ingest directory since it should now be empty
	    rmdir($ingest) or return "Unable to remove $ingest directory.";
	    printf($LOG "Removed directory: %s\n", $ingest);
	} else {
	    # Error message when the tar ball could not be created.
	    return "Could not create the ceopavn tar file: $file";
	}
    } else {
	# Error message when the ingest directory cannot be found.
	return "Ingest directory for ceopavn ($ingest) does not exist.";
    }

    # No errors, so return empty string.
    return "";
}

##-------------------------------------------------------------------------------------------
# @signature String archive_data()
# <p>Create the tar balls for the data and put them on the mass store.  Once the data is
# on the mass store, email Chi-Fan that the data is ready.</p>
#
# @output $err The error message generated by creating the tar ball, or an empty string
# if there are no errors to report.
##-------------------------------------------------------------------------------------------
sub archive_data {
    my $self = shift;
    my $report = "";

    # Create the ceopavn tar ball.
    my $msg = $self->archive_ceopavn();
    $report .= sprintf("\n%s",$msg) if ($msg ne "");

    # Put the ceopavn tar ball on the mass store.
    $msg = $self->mass_store_ceopavn();
    $report .= sprintf("\n%s",$msg) if ($msg ne "");

    # Create the ncep tar ball.
    $msg = $self->archive_ncep();
    $report .= sprintf("\n%s",$msg) if ($msg ne "");

    # Put the ncep tar ball on the mass store.
    $msg = $self->mass_store_ncep();
    $report .= sprintf("\n%s",$msg) if ($msg ne "");

    # Email chifan that the data is ready.
    if ($msg eq "") {
	$msg = $self->email_chifan();
	$report .= sprintf("\n%s",$msg) if ($msg ne "");
    } else {
	$report .= sprintf("\nAn error occurred in the archiving, so the email to Chi-Fan was not sent.");
    }

    return $report ne "" ? substr($report,1) : $report;
}

##-------------------------------------------------------------------------------------------
# @output $err The error message generated by creating the tar ball, or an empty string
# if there are no errors to report.
##-------------------------------------------------------------------------------------------
sub archive_ncep {
    my $self = shift;
    my $ingest = sprintf("%s/ingest/%04d/%02d",NcepUtil::ncep_home(),$self->{"year"},
			 $self->{"month"});

    if (-e $ingest) {
	
	my $cur_dir = cwd();
	chdir($ingest) or return "Unable to change to $ingest.";
	printf($LOG "Changed to %s directory.\n",$ingest);

	my $archive = sprintf("%s/archive/%04d",NcepUtil::ncep_home(),$self->{"year"});
	my $file = sprintf("katz_%s%04d.tar",NcepUtil::monthAbbrev($self->{"month"}),
			   $self->{"year"});

	NcepUtil::create_directory($archive);
	printf($LOG "Create directory: %s\n",$archive);

	my $out_file = sprintf("%s/logs/%04d/%s%04d.log",NcepUtil::ncep_home(),$self->{"year"},
			     NcepUtil::monthAbbrev($self->{"month"}),
			       $self->{"year"});

	if (-e sprintf("%s/%s",$archive,$file)) {
	    printf($LOG "$file already exists.  Deleting and remaking.\n");
	    unlink(sprintf("%s/%s",$archive,$file));
	}

	if (NcepUtil::tar(sprintf("%s/%s",$archive,$file),
			  sprintf("%s%04d",NcepUtil::monthAbbrev($self->{"month"}),
				  $self->{"year"}), $out_file) == 0) {
	    printf($LOG "Created katz tar file: %s",$file);

	    # These files need to go to codiac, so don't delete them yet.
	} else {
	    return "Could not create the katz tar file: $file";
	}

	chdir($cur_dir) or return "Unable to return to $cur_dir.";
	printf($LOG "Changed to directory: %s\n",$cur_dir);
    } else {
	return "Ingest directory does not exist. ($ingest)";
    }

    return "";
}

##-------------------------------------------------------------------------------------------
# @signature void close()
# <p>Close down the archive module and remove all of the empty directories.</p>
##-------------------------------------------------------------------------------------------
sub close {
    my $self = shift;

    my ($YEAR,$ARCHIVE);
    my $dir = sprintf("%s/archive/%04d",NcepUtil::ncep_home(),$self->{"year"});
    opendir($YEAR,$dir) or printf($LOG "Could not read %s directory\n",$dir);
    if (scalar(grep(!/^\./,readdir($YEAR))) == 0) {
	printf($LOG "Removed directory: %s\n",$dir) if (rmdir($dir));
	
	my $dir = sprintf("%s/archive",NcepUtil::ncep_home());
	opendir($ARCHIVE,$dir) or printf($LOG "Could not read %s directory\n",$dir);
	if (scalar(grep(!/^\./,readdir($ARCHIVE))) == 0) {
	    printf($LOG "Removed directory: %s\n",$dir) if (rmdir($dir));
	    
	}
	closedir($ARCHIVE);
    }
    closedir($YEAR);

    close($LOG);
}

##-------------------------------------------------------------------------------------------
# @signature String email_chifan()
# <p>Send an email to Chi-Fan to let him know that the data is ready for him on the mass store.</p>
#
# @output $msg The results of sending the message.
##-------------------------------------------------------------------------------------------
sub email_chifan {
    my $self = shift;
    my $to_address = "chifan\@ucar.edu";
#    my $to_address = "jclawson\@joss.ucar.edu";
    my $month = NcepUtil::monthAbbrev($self->{"month"});
    my $file = sprintf("katz_%s%04d.tar",$month,$self->{"year"});

    printf($LOG "Sending file (%s) to (%s,%s) to tell that it is on the mass store.\n",
	   $file,$to_address,NcepUtil::addresses());

    return NcepUtil::send_mail(sprintf("Chi-Fan,\n\nThe NCEP/EMC data for %s %04d are on the MSS.  The file is called %s/%s.  A listing of the contents of this tarfile is attached.\n",$month,$self->{"year"},NcepUtil::dssMSS(),$file),sprintf("Sid Katz %s %04d Data",$month,$self->{"year"}),$to_address,NcepUtil::addresses(),sprintf("%s/logs/%04d/%s%04d.log",NcepUtil::ncep_home(),$self->{"year"},$month,$self->{"year"}));
}

##-------------------------------------------------------------------------------------------
# @output $err The error message generated by creating the tar ball, or an empty string
# if there are no errors to report.
##-------------------------------------------------------------------------------------------
sub mass_store_ceopavn {
    my $self = shift;
    my $file = sprintf("ceopavn.%04d%02d.tar",$self->{"year"},$self->{"month"});


    if (NcepUtil::mass_store(sprintf("%s/archive/%04d/%s",NcepUtil::ncep_home(),
				     $self->{"year"},$file),
			     sprintf("%s/%s",NcepUtil::jossMSS($self->{"year"}),
				     $file), "-wpwd jossdata") == 0) {

#    if (1) {

	printf($LOG "Put file (%s) on the mass store.\n",$file);
	
	my $archive = sprintf("%s/archive/%04d/%s",NcepUtil::ncep_home(),$self->{"year"},$file);
#	printf($LOG "Removed file: %s\n",$archive) if (unlink($archive));
	return "";
    } else {
	return sprintf("Unable to put file (%s) on the mass store.",$file);
    }
}

##-------------------------------------------------------------------------------------------
# @output $err The error message generated by creating the tar ball, or an empty string
# if there are no errors to report.
##-------------------------------------------------------------------------------------------
sub mass_store_ncep {
    my $self = shift;
    my $file = sprintf("katz_%s%04d.tar",NcepUtil::monthAbbrev($self->{"month"}),
		       $self->{"year"});

    if (NcepUtil::mass_store(sprintf("%s/archive/%04d/%s",NcepUtil::ncep_home(),
				     $self->{"year"},$file),
			     sprintf("%s/%s",NcepUtil::dssMSS(),$file), "") == 0) {

#    if (1) {

	printf($LOG "Put file (%s) on the mass store.\n",$file);

	my $archive = sprintf("%s/archive/%04d/%s",NcepUtil::ncep_home(),$self->{"year"},$file);
#	printf($LOG "Removed file: %s\n",$archive) if (unlink($archive));
	return "";
    } else {
	return sprintf("Unable to put file (%s) on the mass store.",$file);
    }
}

##-------------------------------------------------------------------------------------------
# @signature NcepArchive new(int month, int year)
# <p>Create a new module that can archive tar balls to the mass store and uncompress the
# downloaded data so it can be put into /archive/codiac.
#
# @input $month The month of the archiving.
# @input $year The year of the month.
# @output $archive The archiving module.
##-------------------------------------------------------------------------------------------
sub new {
    my $invocant = shift;
    my $self = {};
    my $class = ref($invocant) || $invocant;
    bless($self,$class);

    # Die if invalid parameters
    die("Invalid arguements to NcepArchive->new.  Must have month and year.\n")
	if (scalar(@_) != 2);

    $self->{"month"} = $_[0];
    $self->{"year"} = $_[1];
    $self->{"addresses"} = NcepUtil::addresses();

    open($LOG, sprintf(">%s/logs/%04d/Archive%04d%02d.log",NcepUtil::ncep_home(),$self->{"year"},
		       $self->{"year"},$self->{"month"}));

    return $self;
}

##-------------------------------------------------------------------------------------------
# @output $err The error message generated by creating the tar ball, or an empty string
# if there are no errors to report.
##-------------------------------------------------------------------------------------------
sub uncompress_data {
    my $self = shift;
    my $report = "";

    my $msg = $self->uncompress_hrly_prcp();
    $report .= sprintf("\n%s", $msg) if ($msg ne "");

    $msg = $self->uncompress_dly_prcp();
    $report .= sprintf("\n%s", $msg) if ($msg ne "");

    $msg = $self->uncompress_snapshot();
    $report .= sprintf("\n%s", $msg) if ($msg ne "");

    $msg = $self->uncompress_stage4();
    $report .= sprintf("\n%s", $msg) if ($msg ne "");

    $msg = $self->uncompress_st2_4km();
    $report .= sprintf("\n%s", $msg) if ($msg ne "");

    rmdir(sprintf("%s/ingest/%04d/%02d/%s%04d",NcepUtil::ncep_home(),$self->{"year"},$self->{"month"},
		NcepUtil::monthAbbrev($self->{"month"}),$self->{"year"})) or
		    $report .= sprintf("Unable to remove %s%04d directory",
				     NcepUtil::monthAbbrev($self>{"month"},$self->{"year"}));

    return $report ne "" ? substr($report,1) : $report;
}

##-------------------------------------------------------------------------------------------
# @output $err The error message generated by creating the tar ball, or an empty string
# if there are no errors to report.
##-------------------------------------------------------------------------------------------
sub uncompress_dly_prcp {
    my $self = shift;

    my $month = sprintf("%s%04d",NcepUtil::monthAbbrev($self->{"month"}),$self->{"year"});
    my $dir = sprintf("%s/ingest/%04d/%02d/dly_prcp",NcepUtil::ncep_home(),$self->{"year"},$self->{"month"});
    my $tar_file = sprintf("%s/ingest/%04d/%02d/%s/prcp.dly.%s",NcepUtil::ncep_home(),$self->{"year"},
		       $self->{"month"},$month,$month);

    NcepUtil::create_directory($dir) if (!(-e $dir));

    my $cur_dir = cwd();
    chdir($dir) or return "Unable to change to $dir";
    printf($LOG "Changing to %s directory\n",$dir);

    if (NcepUtil::untar($tar_file) == 0) {
	my $DLY;
	my $msg = "";
	opendir($DLY,$dir) or return "Cannot read files in $dir";
	foreach my $file (sort(readdir($DLY))) {
	    if ($file =~ /^gage\.dly\.prcp/) {
		if (NcepUtil::uncompress($file) != 0) {
		    my $tmp_msg = "Unable to uncompress $file";
		    $msg .= $msg eq "" ? $tmp_msg : sprintf("\n%s",$tmp_msg);
		} else {
		    printf($LOG "Uncompressed file: %s\n",$file);
		}
	    }
	}
	closedir($DLY);

	return $msg if ($msg ne "");

	unlink($tar_file) or return "Unable to remove file $tar_file";
	printf($LOG "Removed file: %s\n",$tar_file);
    } else {
	chdir($cur_dir);
        return "Unable to untar $tar_file";
    }
	    

    chdir($cur_dir) or return "Unable to change back to $cur_dir";
    return "";
}

##-------------------------------------------------------------------------------------------
# @output $err The error message generated by creating the tar ball, or an empty string
# if there are no errors to report.
##-------------------------------------------------------------------------------------------
sub uncompress_hrly_prcp {
    my $self = shift;

    my $month = sprintf("%s%04d",NcepUtil::monthAbbrev($self->{"month"}),$self->{"year"});
    my $dir = sprintf("%s/ingest/%04d/%02d/hrly_prcp",NcepUtil::ncep_home(),$self->{"year"},$self->{"month"});
    my $tar_file = sprintf("%s/ingest/%04d/%02d/%s/prcp.hrly.%s",NcepUtil::ncep_home(),$self->{"year"},
		       $self->{"month"},$month,$month);

    NcepUtil::create_directory($dir) if (!(-e $dir));
    printf($LOG "Created directory: %s\n",$dir);

    my $cur_dir = cwd();
    chdir($dir) or return "Unable to change to $dir";
    printf($LOG "Changed to %s directory\n", $dir);

    if (NcepUtil::untar($tar_file) == 0) {
	my $HRLY;
	my $msg = "";
	opendir($HRLY,$dir) or return "Cannot read files in $dir";
	foreach my $file (sort(readdir($HRLY))) {
	    if ($file =~ /^gage\.hrly\.prcp/) {
		if (NcepUtil::uncompress($file) != 0) {
		    my $tmp_msg = "Unable to uncompress $file";
		    $msg .= $msg eq "" ? $tmp_msg : sprintf("\n%s",$tmp_msg);
		} else {
		    printf($LOG "Uncompressed file: %s\n",$file);
		}
	    }
	}
	closedir($HRLY);

	return $msg if ($msg ne "");

	unlink($tar_file) or return "Unable to remove file $tar_file";
	printf($LOG "Removed file: %s\n",$tar_file);
    } else {
	chdir($cur_dir);
        return "Unable to untar $tar_file";
    }
	    

    chdir($cur_dir) or return "Unable to change back to $cur_dir";
    printf($LOG "Changed to %s directory\n",$cur_dir);
    return "";
}

##-------------------------------------------------------------------------------------------
# @output $err The error message generated by creating the tar ball, or an empty string
# if there are no errors to report.
##-------------------------------------------------------------------------------------------
sub uncompress_snapshot {
    my $self = shift;

    my $month = sprintf("%s%04d",NcepUtil::monthAbbrev($self->{"month"}),$self->{"year"});
    my $dir = sprintf("%s/ingest/%04d/%02d/snapshot",NcepUtil::ncep_home(),$self->{"year"},$self->{"month"});
    my $tar_file = sprintf("%s/ingest/%04d/%02d/%s/snapshot.%s",NcepUtil::ncep_home(),$self->{"year"},
		       $self->{"month"},$month,$month);

    NcepUtil::create_directory($dir) unless(-e $dir);
    printf($LOG "Created directory: %s\n",$dir);

    my $cur_dir = cwd();
    chdir($dir) or return "Unable to change to $dir";

    if (NcepUtil::untar($tar_file) == 0) {
	my $SNAP;
	my $msg = "";
	opendir($SNAP,$dir) or return "Cannot read files in $dir";
	foreach my $file (sort(readdir($SNAP))) {
	    if ($file =~ /^ST2_vu/) {
		if (NcepUtil::untar($file) != 0) {
		    my $tmp_msg = "Unable to untar $file";
		    $msg .= $msg eq "" ? $tmp_msg : sprintf("\n%s",$tmp_msg);
		} else {
		    printf($LOG "Untarred file: %s\n", $file);
		    printf($LOG "Removed file: %s\n", $file) if (unlink($file));
		}
	    }
	}
	closedir($SNAP);

	return $msg if ($msg ne "");

	unlink($tar_file) or return "Unable to remove file $tar_file";
	printf($LOG "Removed file: %s\n",$tar_file);
    } else {
	chdir($cur_dir);
        return "Unable to untar $tar_file";
    }
	    

    chdir($cur_dir) or return "Unable to change back to $cur_dir";
    printf($LOG "Changed to %s directory\n",$cur_dir);
    return "";
}

##-------------------------------------------------------------------------------------------
# @output $err The error message generated by creating the tar ball, or an empty string
# if there are no errors to report.
##-------------------------------------------------------------------------------------------
sub uncompress_st2_4km {
    my $self = shift;
    
    my $month = sprintf("%s%04d",NcepUtil::monthAbbrev($self->{"month"}),$self->{"year"});
    my $dir = sprintf("%s/ingest/%04d/%02d/st2_4km",NcepUtil::ncep_home(),$self->{"year"},$self->{"month"});

  NcepUtil::create_directory($dir) if (!(-e $dir));
    printf($LOG "Created directory: %s\n",$dir);
	  
    my $cur_dir = cwd();
    chdir($dir) or return "Unable to change to $dir";
    printf($LOG "Changed to %s directory\n",$dir);

    my $msg = "";

    for (my $i = 1; $i <= NcepUtil::get_days_in_month($self->{"month"},$self->{"year"}); $i++) {
	my $file = sprintf("%s/ingest/%04d/%02d/%s/ST2_4km.%04d%02d%02d",NcepUtil::ncep_home(),
			   $self->{"year"},$self->{"month"},$month,$self->{"year"},
			   $self->{"month"},$i);

	if (NcepUtil::untar($file) != 0) {
	    my $tmp_msg = "Unable to untar $file";
	    $msg .= $msg eq "" ? $tmp_msg : sprintf("\n%s",$tmp_msg);
	} else {
	    printf($LOG "Untarred file: %s\n",$file);
	    printf($LOG "Removed file: %s\n",$file) if (unlink($file));
	}
    }
    
    return $msg if ($msg ne "");

    chdir($cur_dir) or return "Unable to change back to $cur_dir";
    printf($LOG "Changed to %s directory\n",$cur_dir);
    return "";
}

##-------------------------------------------------------------------------------------------
# @output $err The error message generated by creating the tar ball, or an empty string
# if there are no errors to report.
##-------------------------------------------------------------------------------------------
sub uncompress_stage4 {
    my $self = shift;

    my $month = sprintf("%s%04d",NcepUtil::monthAbbrev($self->{"month"}),$self->{"year"});
    my $dir = sprintf("%s/ingest/%04d/%02d/stage4",NcepUtil::ncep_home(),$self->{"year"},$self->{"month"});
    my $tar_file = sprintf("%s/ingest/%04d/%02d/%s/stage4.%s",NcepUtil::ncep_home(),$self->{"year"},
		       $self->{"month"},$month,$month);

    NcepUtil::create_directory($dir) if (!(-e $dir));
    printf($LOG "Created directory: %s\n", $dir);

    my $cur_dir = cwd();
    chdir($dir) or return "Unable to change to $dir";
    printf($LOG "Changed to %s directory\n",$dir);

    if (NcepUtil::untar($tar_file) == 0) {
	my $STAGE;
	my $msg = "";
	opendir($STAGE,$dir) or return "Cannot read files in $dir";
	foreach my $file (sort(readdir($STAGE))) {
	    if ($file =~ /^ST4/) {
		if (NcepUtil::untar($file) != 0) {
		    my $tmp_msg = "Unable to untar $file";
		    $msg .= $msg eq "" ? $tmp_msg : sprintf("\n%s",$tmp_msg);
		} else {
		    printf($LOG "Untarred file: %s\n",$file);
		    printf($LOG "Removed file: %s\n",$file) if (unlink($file));
		}
	    }
	}
	closedir($STAGE);

	return $msg if ($msg ne "");

	unlink($tar_file) or return "Unable to remove file $tar_file";
	printf($LOG "Removed file: %s\n", $tar_file);
    } else {
	chdir($cur_dir);
        return "Unable to untar $tar_file";
    }
	    

    chdir($cur_dir) or return "Unable to change back to $cur_dir";
    printf($LOG "Changed to %s directory\n", $cur_dir);
    return "";
}

1;





