#!/usr/bin/perl -w

package Util;

use lib ".";
use Heading;

use CGI qw(:standard :html3 );
require Exporter;
use vars qw(@ISA @EXPORT $VERSION );


@ISA = qw(Exporter);
@EXPORT = qw( $td $tde $td1 $td2 $td3 $tr $tre @headings &println $my_url $warningMessage $yellow );

$td = "<td>";
$tde = "</td>";
$td1 = "<td align=left>";
$td2 = "<td align=center>";
$td3 = "<td align=right>";
$tr = "<tr>";
$tre = "</tr>";

# Heading->new( title, headingIsACategory, category1, category2, ... );

@headings = ( Heading->new( "Aircraft", 1, 1 ), 
							Heading->new( "GPS", 1, 2 ), 
							Heading->new( "Land", 1, 3 ), 
							Heading->new( "Lidar", 1, 4 ), 
							Heading->new( "Mesonet", 0, 5, 6, 7, 8 ), 
							Heading->new( "Model", 1, 9 ), 
							Heading->new( "Photography", 1, 10 ), 
							Heading->new( "Profiler/SODAR", 1, 11 ), 
							Heading->new( "Radar", 1, 12 ), 
							Heading->new( "Radiation", 1, 13 ), 
							Heading->new( "Satellite", 1, 14 ), 
							Heading->new( "Soundings", 1, 15 ), 
						); 

sub println
{
	print( @_, "\n" );
}


$warningMessage = "\n\n<!--\n" .
									"=====================================================================================\n".
									"WARNING:  This is not a normal .html page!  This page\n" .
									"is generated by a perl script and should not be edited\n".
									"If you want to edit this page go to $my_url.\n".
									"If you have any questions talk to Don Stott or Dan Sullivan\n".	
									"=====================================================================================\n".
									"-->\n\n";

$yellow = "#FFFFCC";
1;
