#!/usr/bin/perl -w

# spoolACARStest
# mark, 2004 June 4
# sean, 2010 July 14
#
# $Id: spoolACARS,v 1.3 2004/06/05 06:08:54 joss Exp joss $
# $Log: spoolACARS,v $
#
#  @author Linda Echo-Hawk
#  @version 2.0 22 March 2021
#  Revised the MySqlDatabase constructor to pass in the  ~/.my.cnf file
#  containing the dbase and password rather than having these hard-coded
#  in the script. This solved a security issue.
#
# Revision 1.6 1018/10/29 echohawk
# Changed @monitors from empty string to eol-cds-ingest
# to conform with other ingest scripts about who receives
# email notifications. 
#
# Revision 1.5 2018/09/07 echohawk
# Commented out system RM commands. Changes to the LDM server
# in 2018 resulted in LDM no longer creating group writeable
# directories so this script can no longer remove files. This
# change should reduce the number of error messages received
# until a better fix is in place. Currently John Allison is
# running an LDM scrubber to remove the files.
#
# Revision 1.4 2010/07/14 stroble
# Added ability to insert files into Codiac automatically
#
# Revision 1.3  2004/06/05 06:08:54  joss
# Remove testing stubs.
#
# Revision 1.2  2004/06/04 18:05:47  joss
# Overhaul of script to directly send data to MSS
#
#
# Script to automatically spool compressed netCDF ACARS data to MSS
#
# Data is already gzipped, so daily tarfiles (~100M each) will be stored to
# /JOSS/DATA/RAW/SOUNDING/ACARS/YYYY where YYYY is the year.  Filenames
# will be acars.YYYYMMDD.tar where YYYYMMDD is the file date.
#
# File will run once per day.

use strict;
use lib "/net/work/lib/perl/mysql";
use lib "/net/work/lib/perl/mail";
use lib "/net/work/lib/perl/hpss";
#use lib "/h/eol/dmg/HPSS_cronjobs/lib";
use Time::Local;
use POSIX "strftime";
use FindBin qw($Script $Bin);
use MySqlDatabase;
use MySqlDataset;
use MySqlFile;
use HPSS;
use MAIL;

# Constants
my $dataset_id = "100.016";
my $srcdir='/export/ldm/data/acars/netcdf';
my $tmp='/scr/tmp/joss/acars';
my $destdir='/FS/EOL/operational/aircraft/acars';
my @monitors = ('eol-cds-ingest@ucar.edu');
my $report_header = "";
my $report = "";
my $TAR='/bin/tar';
my $RM='/bin/rm';
my $RMDIR='/bin/rmdir --ignore-fail-on-non-empty'; # GNU rmdir can be quiet!

$report_header .= "I am $Bin/$Script running on ".`/bin/hostname`."\n";


chdir($srcdir) or die "Couldn't cd to $srcdir, $!";
$report_header .= "working from $srcdir\n";

# Figure out day before yesterday:
my ($day, $month, $year) = (gmtime(time-2*86400))[3,4,5];
my $dby = sprintf("%04d%02d%02d", $year+1900, $month+1, $day);
my $today=int(time()/86400);
$report_header .= "Spooling ACARS older than $dby (UTC)\n";

my @years=glob('????');
foreach $year (@years) {
    opendir(DIR,$year);
    my @days=sort(grep(/^\d{8}$/,readdir(DIR)));
    closedir(DIR);
    #print "Year: $year Days: @days\n";

    foreach $day (@days) {
        my ($y, $m, $d)=$day=~/^(\d\d\d\d)(\d\d)(\d\d)$/;
        #print "y, m, d: $y, $m, $d\n";
        my $thisday=int(timegm(0,0,0,$d,$m-1,$y-1900)/86400);
        #print "today, thisday: $today, $thisday\n";
	#give it 2 days to finish collecting data to be safe
	next if ($today-$thisday) <= 2;

	#$report .= "Spooling files from $day\n";

        my $f="$tmp/acars.$day.tar";
	#$report .= "$TAR cf $f $year/$day\n";
	my $result=system("$TAR cf $f $year/$day");
	if ($result) {
	    $report .= "ERROR $result in tar!\n";
	    next;
	}

    if (! HPSS::exists("$destdir/$year/acars.$day.tar")  ) {

	#$report .= "HPSS put job: $f hpss:$destdir/$year/acars.$day.tar\n";
	$result = HPSS::put(\$f, \"$destdir/$year/acars.$day.tar");
	if ($result) {
	    $report .= "ERROR $result in hpss_put!\n";
	    #next;
	}

	#$report .= "Inserting $destdir/$year/acars.$day.tar to dataset $dataset_id";
	# Create and open the database
	my $database = MySqlDatabase->new(); # use ~/.my.cnf
	
	my $mysqlFile = MySqlFile->new();
	$mysqlFile->setHost("hpss");
	$mysqlFile->setDatasetArchiveIdent("$dataset_id");
	$mysqlFile->setFile("$destdir/$year", "acars.$day.tar");
	$mysqlFile->setFormatId(53);
	$mysqlFile->setBeginDate($y,$m,$d,0,0,0);
	$mysqlFile->setEndDate($y,$m,$d,23,59,59);

	$database->connect();
	my $msg = $mysqlFile->insert($database);

	#if insert worked
	if ($msg eq "") { $msg .= $database->commit(); }
	#else undo
	else { $msg.= "Database rolled back.\n".$database->rollback(); }
	
	$database->disconnect();

	$report .= $msg;	

	} # end if (! HPSS::exists("$destdir/$year/acars.$day.tar"))

	
	if (! HPSS::exists("$destdir/$year/acars.$day.tar")  ) {
	    $report .= "/n$destdir/$year/acars.$day.tar does not exist!\n";
	    next;
	}

	system("$RM $f");
	# In 2018, LDM created directories that were no longer group
	# writeable and we were not able to remove them with this
	# script. I commented out the two lines below in order to
	# minimize the resulting error emails.
	# system("$RM -r $year/$day");
	# system("$RMDIR $year"); # Will only succeed when $year empty
    }

    # Send out an email that the script has finished.
    if ($report ne "") { sendMailAndDie($report_header.$report); }
    #else { sendMailAndDie("There are no errors to report"); }

}
sub sendMailAndDie {
    my ($body) = @_;
    MAIL::send_mail("$Script Script Error\n",$body, @monitors);
    exit(1);
}

