#!/usr/bin/perl

#---------------------------------------------------
# calc_range_limits.pl - this PERL script
#   calculates the limit values for table 3-2
#   used in the surface description documents
#   for datasets that have been HQC'd. This
#   program allows the user to manually "fiddle"
#   with the values and determine the best set.
#
# input: variance range low limit then range  
#   high limit. These high and low limits
#   can be taken from or calculated from 
#   the limit bins output in the var_ct.out
#   file created by C program compute_var_cts.
#   The compute_var_cts program does the
#   same calcs as this perl program but for
#   the set of bins that it determines to
#   contain %95 of the variances for each
#   parameter. The user can take the bins
#   generated by the C program and determine
#   the set of bins that they believe contains
#   %95 of the variances. Then the user can
#   input the max and min (high, low) bin (i.e.,
#   variance) values into this program. Then this 
#   Perl program will compute a line for the speci-
#   fied Table 3-2 for the documentation. This Perl
#   program was created so the user could "fiddle"
#   with the %95 range of bin limits and determine
#   the best set of bins. The C program may not
#   determine the best set of bins containing %95,
#   but it generally works well.
#
# output: Values for Table 3-2 in sfc 
#   description documents. 
#
# WARNING: The user must ensure that the alpha
#   values are correct for the current project.
#   They should be the exact same alpha values
#   used during HQCing the data.
#
# 12 June 98 lec
#   Created.
#---------------------------------------------------

#-----------------------------
# First get and print the time
#-----------------------------
($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
printf "calc_range_limits began at $year/$mon/$mday $hour:$min:$sec\n";

#-----------------------------
# These are the Good and Bad
# (or unlikely) alpha values
# used during the HQC process.
#-----------------------------
@alpha_G = (0.2, 0.2, 0.4, 0.5, 0.5, 2.25, 1.22);  # ESOP and NESOB 1996.
@alpha_B = (0.5, 0.5, 1.0, 1.0, 1.0, 4.0,  2.2);   # ESOP and NESOB 1996

#-------------------------------------
# Prompt user for high and low limits. 
#-------------------------------------
printf "Enter parameter number.\n";
printf "(0=stnP,1=SLP,2=CSLP,3=Temp,4=DewPt,5=WindSp,6=WindDir)\n";
$parm = <STDIN>;
chop ($parm); # Chop of the trailing return.

printf "Enter Low variance limit: ";
$low = <STDIN>;
chop ($low);

printf "Enter High variance limit: ";
$high = <STDIN>;
chop ($high);

print "Low= $low and High= $high.\n";

#----------------------------
# Calculate Table 3-2 values.
#----------------------------
$good = $alpha_G[$parm]* sqrt($high); #Highest Good value
  
$questionable_low = $alpha_G[$parm]*sqrt($low);
$questionable_hi  = $alpha_B[$parm]*sqrt($high);

$unlikely = $alpha_B[$parm]* sqrt($low); #Lowest Bad value

#-------------------------
# Output Table 3-2 values.
#-------------------------
printf "\nParmNum  Good    Q_low   Q_high  Unlikely\n";

printf ("%5d %7.2f %7.2f %7.2f %7.2f\n",
       $parm, $good, $questionable_low, $questionable_hi, $unlikely);


($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
printf "calc_range_limits ended at $year/$mon/$mday $hour:$min:$sec\n";
