#!/bin/sh

insert_db ACE-ASIA ace-asia/dln.dat ace-asia/ml.dat ace-asia/cats.dat
insert_db DYCOMS-II dycoms/dln.dat dycoms/ml.dat dycoms/cats.dat
insert_db EPIC epic/dln.dat epic/ml.dat epic/cats.dat
insert_db INDOEX indoex/dln_all.dat indoex/ml.dat indoex/cats.dat
insert_db PACS pacs/dln.dat pacs/ml.dat pacs/cats.dat
